using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game.Scripts.Main.Editor.Protobuf
{
    public class CeleritasGeneratorInstance
    {
        private readonly Dictionary<string, ProtoMessage> _messages = new();
        private readonly string _outputDirAbs = Path.Combine(Application.dataPath, "Game", "Scripts", "Hotfix", "HotfixCommon", "Network", "Packet", "CSCeleritas.cs");
        private readonly string _protoRootAbs = Path.Combine(Application.dataPath, "Game", "proto");

        public void Run()
        {
            ParseProtoFiles();
            GenerateCeleritasClass();
            RefreshAssetDatabase();
        }

        private void ParseProtoFiles()
        {
            _messages.Clear();
            ParseAllProto(_protoRootAbs);
        }

        private void GenerateCeleritasClass()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.Append(GenerateFileHeader());
            stringBuilder.Append(GenerateClassOpening());

            var rootMessage = FindMessage("client_request");
            if (rootMessage != null)
            {
                stringBuilder.Append(GenerateMethods(rootMessage,
                    new List<ProtoField>(),
                    "Celeritas.CeleritasRequest.Client"));
            }
            else
            {
                Debug.LogError("Could not find client_request message.");
                return;
            }

            stringBuilder.Append(GenerateClassClosing());

            File.WriteAllText(_outputDirAbs, stringBuilder.ToString());
        }

        private static StringBuilder GenerateFileHeader()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("// <auto-generated>");
            stringBuilder.AppendLine("//     This code was generated by a tool.");
            stringBuilder.AppendLine("//     Do not modify");
            stringBuilder.AppendLine("// </auto-generated>");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("using System;");
            stringBuilder.AppendLine("using Celeritas.Proto;");
            stringBuilder.AppendLine("using Celeritas.Proto.Client;");
            stringBuilder.AppendLine("using Celeritas.Proto.Common;");
            stringBuilder.AppendLine("using ProtoBuf;");
            stringBuilder.AppendLine();

            return stringBuilder;
        }

        private static StringBuilder GenerateClassOpening()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("namespace Game.Scripts.Hotfix.HotfixCommon.Network.Packet");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    [Serializable]");
            stringBuilder.AppendLine("    [ProtoContract(Name = @\"CSCeleritas\")]");
            stringBuilder.AppendLine("    public class CSCeleritas : CSPacketBase");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine("        public CSCeleritas()");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            Common = new header();");
            stringBuilder.AppendLine("            Celeritas = new celeritas");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                CeleritasRequest = new request");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine("                    Client = new client_request()");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine("            };");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        public override int Id => 100;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        public header Common { get; set; }");
            stringBuilder.AppendLine("        public celeritas Celeritas { get; set; }");
            stringBuilder.AppendLine();

            return stringBuilder;
        }

        private static StringBuilder GenerateClassClosing()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("        public override void Clear()");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            Common = new header();");
            stringBuilder.AppendLine("            Celeritas = new celeritas");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                CeleritasRequest = new request");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine("                    Client = new client_request()");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine("            };");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");

            return stringBuilder;
        }

        private static void RefreshAssetDatabase()
        {
            AssetDatabase.Refresh();
        }

        private StringBuilder GenerateMethods(ProtoMessage msg, List<ProtoField> path, string propertyPath)
        {
            var stringBuilder = new StringBuilder();
            foreach (var field in msg.Fields.Where(field => !string.IsNullOrEmpty(field.OneOfGroup)))
            {
                stringBuilder.Append(ProcessField(field, path, propertyPath));
            }

            return stringBuilder;
        }

        private StringBuilder ProcessField(ProtoField field, List<ProtoField> path, string propertyPath)
        {
            var stringBuilder = new StringBuilder();
            var currentPath = new List<ProtoField>(path) { field };

            var methodName = GetMethodName(currentPath);
            var fieldType = field.Type;
            var returnType = GetCSharpTypeName(fieldType);
            var fieldPropertyName = ToPascalCase(field.Name);
            var newPropertyPath = propertyPath + "." + fieldPropertyName;

            var childMessage = FindMessage(fieldType);
            var isLeaf = IsLeafNode(childMessage);

            stringBuilder.Append(GenerateMethodCode(methodName, returnType, newPropertyPath, path, isLeaf));

            if (childMessage != null)
            {
                stringBuilder.Append(GenerateMethods(childMessage, currentPath, newPropertyPath));
            }

            return stringBuilder;
        }

        private static bool IsLeafNode(ProtoMessage childMessage)
        {
            if (childMessage == null)
            {
                return true;
            }

            var hasOneOf = false;
            var allOneOfAreReqOrRes = true;

            foreach (var childField in childMessage.Fields.Where(childField => !string.IsNullOrEmpty(childField.OneOfGroup)))
            {
                hasOneOf = true;
                var childTypeName = childField.Type.ToLower();
                if (childTypeName.Contains("request") || childTypeName.Contains("response"))
                {
                    continue;
                }

                allOneOfAreReqOrRes = false;
                break;
            }

            return !hasOneOf || !allOneOfAreReqOrRes;
        }

        private static StringBuilder GenerateMethodCode(string methodName, string returnType, string newPropertyPath, List<ProtoField> path, bool isLeaf)
        {
            var stringBuilder = new StringBuilder();
            var accessModifier = isLeaf ? "public" : "private";

            stringBuilder.AppendLine($"        {accessModifier} {returnType} {methodName}()");
            stringBuilder.AppendLine("        {");

            if (path.Count > 0)
            {
                var parentMethodName = GetMethodName(path);
                stringBuilder.AppendLine($"            {parentMethodName}();");
            }

            stringBuilder.AppendLine($"            {newPropertyPath} = new {returnType}();");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"            return {newPropertyPath};");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();

            return stringBuilder;
        }

        private static string GetMethodName(List<ProtoField> path)
        {
            if (path.Count == 0)
            {
                return "";
            }

            var stringBuilder = new StringBuilder("Mutable");
            foreach (var field in path)
            {
                stringBuilder.Append("_");
                stringBuilder.Append(GetCleanTypeName(field.Type));
            }

            return stringBuilder.ToString();
        }

        private static string GetCleanTypeName(string typeName)
        {
            if (typeName.Contains("."))
            {
                typeName = typeName[(typeName.LastIndexOf('.') + 1)..];
            }

            if (typeName.EndsWith("_request"))
            {
                typeName = typeName[..^"_request".Length];
            }

            return ToPascalCase(typeName);
        }

        private static string GetCSharpTypeName(string protoType)
        {
            return protoType.Contains(".") ? protoType[(protoType.LastIndexOf('.') + 1)..] : protoType;
        }

        private static string ToPascalCase(string str)
        {
            if (string.IsNullOrEmpty(str))
            {
                return str;
            }

            var parts = str.Split('_');
            for (var i = 0; i < parts.Length; ++i)
            {
                if (parts[i].Length > 0)
                {
                    parts[i] = char.ToUpper(parts[i][0]) + parts[i][1..];
                }
            }

            return string.Join("", parts);
        }

        private ProtoMessage FindMessage(string name)
        {
            if (_messages.TryGetValue(name, out var message))
            {
                return message;
            }

            foreach (var kvp in _messages)
            {
                if (kvp.Key.EndsWith("." + name) || kvp.Key == name)
                {
                    return kvp.Value;
                }

                var shortName = kvp.Key;
                if (shortName.Contains("."))
                {
                    shortName = shortName[(shortName.LastIndexOf('.') + 1)..];
                }

                if (shortName == name)
                {
                    return kvp.Value;
                }
            }

            return null;
        }

        private void ParseAllProto(string rootPath)
        {
            var files = Directory.GetFiles(rootPath, "*.proto", SearchOption.AllDirectories);
            foreach (var file in files)
            {
                ParseProtoFile(file);
            }
        }

        private void ParseProtoFile(string path)
        {
            var content = File.ReadAllText(path);
            var package = ExtractPackage(content);
            content = RemoveComments(content);

            var lines = content.Split('\n');
            ProcessLines(lines, package);
        }

        private static string ExtractPackage(string content)
        {
            var packageMatch = Regex.Match(content, @"package\s+([\w\.]+);");
            return packageMatch.Success ? packageMatch.Groups[1].Value : "";
        }

        private static string RemoveComments(string content)
        {
            return Regex.Replace(content, "//.*", "");
        }

        private void ProcessLines(string[] lines, string package)
        {
            ProtoMessage currentMessage = null;
            string currentOneOf = null;

            foreach (var element in lines)
            {
                var line = element.Trim();
                if (string.IsNullOrEmpty(line))
                {
                    continue;
                }

                if (line.StartsWith("message "))
                {
                    if (TryProcessMessage(line, package, out var newMessage))
                    {
                        currentMessage = newMessage;
                    }
                }
                else if (line.StartsWith("oneof "))
                {
                    if (TryProcessOneOf(line, currentMessage, out var newOneOf))
                    {
                        currentOneOf = newOneOf;
                    }
                }
                else if (line.Contains("}"))
                {
                    ProcessClosingBrace(line, ref currentOneOf);
                }
                else if (currentMessage != null)
                {
                    ProcessField(line, currentMessage, currentOneOf);
                }
            }
        }

        private bool TryProcessMessage(string line, string package, out ProtoMessage message)
        {
            message = null;
            var match = Regex.Match(line, @"message\s+(\w+)\s*\{?");
            if (!match.Success)
            {
                return false;
            }

            var msgName = match.Groups[1].Value;
            var fullName = string.IsNullOrEmpty(package) ? msgName : package + "." + msgName;
            message = new ProtoMessage { Name = fullName, Package = package };
            _messages[fullName] = message;
            return true;
        }

        private static bool TryProcessOneOf(string line, ProtoMessage currentMessage, out string oneOfName)
        {
            oneOfName = null;
            var match = Regex.Match(line, @"oneof\s+(\w+)\s*\{?");
            if (!match.Success)
            {
                return false;
            }

            oneOfName = match.Groups[1].Value;
            currentMessage?.OneOfs.Add(oneOfName);
            return true;
        }

        private static void ProcessClosingBrace(string line, ref string currentOneOf)
        {
            if (currentOneOf == null)
            {
                return;
            }

            if (line.Contains("}"))
            {
                currentOneOf = null;
            }
        }

        private static void ProcessField(string line, ProtoMessage currentMessage, string currentOneOf)
        {
            var fieldMatch = Regex.Match(line, @"^([\w\.]+)\s+(\w+)\s*=\s*\d+;");
            if (!fieldMatch.Success)
            {
                return;
            }

            var field = new ProtoField
            {
                Type = fieldMatch.Groups[1].Value,
                Name = fieldMatch.Groups[2].Value,
                OneOfGroup = currentOneOf
            };
            currentMessage.Fields.Add(field);
        }
    }
}