using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game.Scripts.Main.Editor.Protobuf
{
    public class CeleritasGeneratorInstance
    {
        private readonly Dictionary<string, ProtoMessage> _messages = new();
        private readonly string _outputDirAbs = Path.Combine(Application.dataPath, "Game/Scripts/Main/Runtime/Network/Packet/CSCeleritas.cs");
        private readonly string _protoRootAbs = Path.Combine(Application.dataPath, "Game", "proto");

        public void Run()
        {
            ParseProtoFiles();
            GenerateCeleritasClass();
            RefreshAssetDatabase();
        }

        private void ParseProtoFiles()
        {
            _messages.Clear();
            ParseAllProto(_protoRootAbs);
        }

        private void GenerateCeleritasClass()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.Append(GenerateFileHeader());
            stringBuilder.Append(GenerateClassOpening());

            var rootMessage = FindMessage("client_request");
            if (rootMessage != null)
            {
                stringBuilder.Append(GenerateMethods(rootMessage, new List<ProtoField>(), "Celeritas.CeleritasRequest.Client"));
            }
            else
            {
                Debug.LogError("Could not find client_request message.");
                return;
            }

            stringBuilder.Append(GenerateClassClosing());

            File.WriteAllText(_outputDirAbs, stringBuilder.ToString());
        }

        private static StringBuilder GenerateFileHeader()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("// <auto-generated>");
            stringBuilder.AppendLine("//     This code was generated by a tool.");
            stringBuilder.AppendLine("//     Do not modify");
            stringBuilder.AppendLine("// </auto-generated>");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("using System;");
            stringBuilder.AppendLine("using Celeritas.Proto;");
            stringBuilder.AppendLine("using Celeritas.Proto.Client;");
            stringBuilder.AppendLine("using Celeritas.Proto.Common;");
            stringBuilder.AppendLine("using ProtoBuf;");
            stringBuilder.AppendLine();

            return stringBuilder;
        }

        private static StringBuilder GenerateClassOpening()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("namespace Game.Scripts.Main.Runtime.Network.Packet");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    [Serializable]");
            stringBuilder.AppendLine("    [ProtoContract(Name = @\"CSCeleritas\")]");
            stringBuilder.AppendLine("    public class CSCeleritas : CSPacketBase");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine("        public CSCeleritas()");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            Common = new header();");
            stringBuilder.AppendLine("            Celeritas = new celeritas");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                CeleritasRequest = new request");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine("                    Client = new client_request()");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine("            };");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        public override int Id => 100;");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("        public header Common { get; set; }");
            stringBuilder.AppendLine("        public celeritas Celeritas { get; set; }");
            stringBuilder.AppendLine();

            return stringBuilder;
        }

        private static StringBuilder GenerateClassClosing()
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("        public override void Clear()");
            stringBuilder.AppendLine("        {");
            stringBuilder.AppendLine("            Common = new header();");
            stringBuilder.AppendLine("            Celeritas = new celeritas");
            stringBuilder.AppendLine("            {");
            stringBuilder.AppendLine("                CeleritasRequest = new request");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine("                    Client = new client_request()");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine("            };");
            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");

            return stringBuilder;
        }

        private static void RefreshAssetDatabase()
        {
            AssetDatabase.Refresh();
        }

        private StringBuilder GenerateMethods(ProtoMessage msg, List<ProtoField> path, string propertyPath)
        {
            var stringBuilder = new StringBuilder();
            foreach (var field in msg.Fields)
            {
                if (string.IsNullOrEmpty(field.OneOfGroup))
                {
                    continue;
                }

                var currentPath = new List<ProtoField>(path) { field };

                var methodName = GetMethodName(currentPath);
                var fieldType = field.Type;
                var returnType = GetCSharpTypeName(fieldType);
                var fieldPropertyName = ToPascalCase(field.Name);
                var newPropertyPath = propertyPath + "." + fieldPropertyName;

                // 判断是否为底层（叶子节点）
                // 规则：
                // 1. 如果没有 oneof，是底层。
                // 2. 如果有 oneof，且所有 oneof 字段的类型都包含 "request" 或 "response"，则不是底层（是路由节点）。
                // 3. 如果有 oneof，但只要有一个字段类型不包含 "request" 或 "response"，则是底层（混合或数据节点）。
                var isLeaf = true;
                var childMessage = FindMessage(fieldType);
                if (childMessage != null)
                {
                    var hasOneOf = false;
                    var allOneOfAreReqOrRes = true;

                    foreach (var childField in childMessage.Fields.Where(childField => !string.IsNullOrEmpty(childField.OneOfGroup)))
                    {
                        hasOneOf = true;
                        var childTypeName = childField.Type.ToLower();
                        if (childTypeName.Contains("request") || childTypeName.Contains("response"))
                        {
                            continue;
                        }

                        allOneOfAreReqOrRes = false;
                        break;
                    }

                    if (hasOneOf && allOneOfAreReqOrRes)
                    {
                        isLeaf = false;
                    }
                }

                var accessModifier = isLeaf ? "public" : "private";

                stringBuilder.AppendLine($"        {accessModifier} {returnType} {methodName}()");
                stringBuilder.AppendLine("        {");

                if (path.Count > 0)
                {
                    var parentMethodName = GetMethodName(path);
                    stringBuilder.AppendLine($"            {parentMethodName}();");
                }

                stringBuilder.AppendLine($"            {newPropertyPath} = new {returnType}();");
                stringBuilder.AppendLine();
                stringBuilder.AppendLine($"            return {newPropertyPath};");
                stringBuilder.AppendLine("        }");
                stringBuilder.AppendLine();

                if (childMessage != null)
                {
                    stringBuilder.Append(GenerateMethods(childMessage, currentPath, newPropertyPath));
                }
            }

            return stringBuilder;
        }

        private static string GetMethodName(List<ProtoField> path)
        {
            if (path.Count == 0)
            {
                return "";
            }

            var stringBuilder = new StringBuilder("Mutable");
            foreach (var field in path)
            {
                stringBuilder.Append("_");
                stringBuilder.Append(GetCleanTypeName(field.Type));
            }

            return stringBuilder.ToString();
        }

        private static string GetCleanTypeName(string typeName)
        {
            if (typeName.Contains("."))
            {
                typeName = typeName[(typeName.LastIndexOf('.') + 1)..];
            }

            if (typeName.EndsWith("_request"))
            {
                typeName = typeName[..^"_request".Length];
            }

            if (!typeName.StartsWith("client_"))
            {
                return ToPascalCase(typeName);
            }

            var withoutClient = typeName["client_".Length..];
            if (withoutClient == "player")
            {
                typeName = withoutClient;
            }

            return ToPascalCase(typeName);
        }

        private static string GetCSharpTypeName(string protoType)
        {
            return protoType.Contains(".") ? protoType[(protoType.LastIndexOf('.') + 1)..] : protoType;
        }

        private static string ToPascalCase(string str)
        {
            if (string.IsNullOrEmpty(str))
            {
                return str;
            }

            var parts = str.Split('_');
            for (var i = 0; i < parts.Length; ++i)
            {
                if (parts[i].Length > 0)
                {
                    parts[i] = char.ToUpper(parts[i][0]) + parts[i][1..];
                }
            }

            return string.Join("", parts);
        }

        private ProtoMessage FindMessage(string name)
        {
            if (_messages.TryGetValue(name, out var message))
            {
                return message;
            }

            foreach (var kvp in _messages)
            {
                if (kvp.Key.EndsWith("." + name) || kvp.Key == name)
                {
                    return kvp.Value;
                }

                var shortName = kvp.Key;
                if (shortName.Contains("."))
                {
                    shortName = shortName[(shortName.LastIndexOf('.') + 1)..];
                }

                if (shortName == name)
                {
                    return kvp.Value;
                }
            }

            return null;
        }

        private void ParseAllProto(string rootPath)
        {
            var files = Directory.GetFiles(rootPath, "*.proto", SearchOption.AllDirectories);
            foreach (var file in files)
            {
                ParseProtoFile(file);
            }
        }

        private void ParseProtoFile(string path)
        {
            var content = File.ReadAllText(path);
            var package = "";

            var packageMatch = Regex.Match(content, @"package\s+([\w\.]+);");
            if (packageMatch.Success)
            {
                package = packageMatch.Groups[1].Value;
            }

            content = Regex.Replace(content, "//.*", "");

            var lines = content.Split('\n');
            ProtoMessage currentMessage = null;
            string currentOneOf = null;

            foreach (var line in lines)
            {
                var l = line.Trim();
                if (string.IsNullOrEmpty(l))
                {
                    continue;
                }

                if (l.StartsWith("message "))
                {
                    var match = Regex.Match(l, @"message\s+(\w+)\s*\{?");
                    if (!match.Success)
                    {
                        continue;
                    }

                    var msgName = match.Groups[1].Value;
                    var fullName = string.IsNullOrEmpty(package) ? msgName : package + "." + msgName;
                    currentMessage = new ProtoMessage { Name = fullName, Package = package };
                    _messages[fullName] = currentMessage;
                }
                else if (l.StartsWith("oneof "))
                {
                    var match = Regex.Match(l, @"oneof\s+(\w+)\s*\{?");
                    if (!match.Success)
                    {
                        continue;
                    }

                    currentOneOf = match.Groups[1].Value;
                    currentMessage?.OneOfs.Add(currentOneOf);
                }
                else if (l.Contains("}"))
                {
                    if (currentOneOf != null)
                    {
                        if (l.Contains("}"))
                        {
                            currentOneOf = null;
                        }
                    }
                    else if (currentMessage != null)
                    {
                        // 消息结束
                    }
                }
                else if (currentMessage != null)
                {
                    var fieldMatch = Regex.Match(l, @"^([\w\.]+)\s+(\w+)\s*=\s*\d+;");
                    if (!fieldMatch.Success)
                    {
                        continue;
                    }

                    var field = new ProtoField
                    {
                        Type = fieldMatch.Groups[1].Value,
                        Name = fieldMatch.Groups[2].Value,
                        OneOfGroup = currentOneOf
                    };
                    currentMessage.Fields.Add(field);
                }
            }
        }
    }
}