using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game.Scripts.Main.Editor.Protobuf
{
    public class CsCeleritasGeneratorInstance
    {
        private readonly Dictionary<string, ProtoMessage> _messages = new();
        private string _protoRootAbs;

        public void Run()
        {
            _protoRootAbs = Path.Combine(Application.dataPath, "Game/proto");
            ParseAllProtos(_protoRootAbs);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("//     Do not modify");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using Celeritas.Proto;");
            sb.AppendLine("using Celeritas.Proto.Client;");
            sb.AppendLine("using Celeritas.Proto.Common;");
            sb.AppendLine("using ProtoBuf;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.Scripts.Main.Runtime.Network.Packet");
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.AppendLine("    [ProtoContract(Name = @\"CSCeleritas\")]");
            sb.AppendLine("    public class CSCeleritas : CSPacketBase");
            sb.AppendLine("    {");
            sb.AppendLine("        public CSCeleritas()");
            sb.AppendLine("        {");
            sb.AppendLine("            Common = new header();");
            sb.AppendLine("            Celeritas = new celeritas");
            sb.AppendLine("            {");
            sb.AppendLine("                CeleritasRequest = new request");
            sb.AppendLine("                {");
            sb.AppendLine("                    Client = new client_request()");
            sb.AppendLine("                }");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public override int Id => 100;");
            sb.AppendLine();
            sb.AppendLine("        public header Common { get; set; }");
            sb.AppendLine("        public celeritas Celeritas { get; set; }");
            sb.AppendLine();

            // 从 client_request 开始生成方法
            var rootMsg = FindMessage("client_request");
            if (rootMsg != null)
            {
                GenerateMethods(sb, rootMsg, new List<ProtoField>(), "Celeritas.CeleritasRequest.Client");
            }
            else
            {
                Debug.LogError("Could not find client_request message.");
            }

            sb.AppendLine("        public override void Clear()");
            sb.AppendLine("        {");
            sb.AppendLine("            Common = new header();");
            sb.AppendLine("            Celeritas = new celeritas");
            sb.AppendLine("            {");
            sb.AppendLine("                CeleritasRequest = new request");
            sb.AppendLine("                {");
            sb.AppendLine("                    Client = new client_request()");
            sb.AppendLine("                }");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var finalPath = Path.Combine(Application.dataPath,
                "Game/Scripts/Main/Runtime/Network/Packet/CSCeleritas.cs");
            File.WriteAllText(finalPath, sb.ToString());
            AssetDatabase.Refresh();
            Debug.Log("CSCeleritas generated successfully.");
        }

        private void GenerateMethods(StringBuilder sb, ProtoMessage msg, List<ProtoField> path, string propertyPath)
        {
            foreach (var field in msg.Fields)
                if (!string.IsNullOrEmpty(field.OneOfGroup))
                {
                    var currentPath = new List<ProtoField>(path);
                    currentPath.Add(field);

                    var methodName = GetMethodName(currentPath);
                    var fieldType = field.Type;
                    var returnType = GetCSharpTypeName(fieldType);
                    var fieldPropertyName = ToPascalCase(field.Name);
                    var newPropertyPath = propertyPath + "." + fieldPropertyName;

                    sb.AppendLine($"        public {returnType} {methodName}()");
                    sb.AppendLine("        {");

                    if (path.Count > 0)
                    {
                        var parentMethodName = GetMethodName(path);
                        sb.AppendLine($"            {parentMethodName}();");
                    }

                    sb.AppendLine($"            {newPropertyPath} = new {returnType}();");
                    sb.AppendLine();
                    sb.AppendLine($"            return {newPropertyPath};");
                    sb.AppendLine("        }");
                    sb.AppendLine();

                    var childMsg = FindMessage(fieldType);
                    if (childMsg != null)
                    {
                        GenerateMethods(sb, childMsg, currentPath, newPropertyPath);
                    }
                }
        }

        private string GetMethodName(List<ProtoField> path)
        {
            if (path.Count == 0)
            {
                return "";
            }

            var first = GetCleanTypeName(path[0].Type);

            if (path.Count == 1)
            {
                return "Set" + first;
            }

            var last = GetCleanTypeName(path[path.Count - 1].Type);
            return "Set" + first + last;
        }

        private string GetCleanTypeName(string typeName)
        {
            if (typeName.Contains("."))
            {
                typeName = typeName.Substring(typeName.LastIndexOf('.') + 1);
            }

            if (typeName.EndsWith("_request"))
            {
                typeName = typeName.Substring(0, typeName.Length - "_request".Length);
            }

            if (typeName.StartsWith("client_"))
            {
                var withoutClient = typeName.Substring("client_".Length);
                if (withoutClient == "player")
                {
                    typeName = withoutClient;
                }
            }

            return ToPascalCase(typeName);
        }

        private string GetCSharpTypeName(string protoType)
        {
            if (protoType.Contains("."))
            {
                return protoType.Substring(protoType.LastIndexOf('.') + 1);
            }

            return protoType;
        }

        private string ToPascalCase(string str)
        {
            if (string.IsNullOrEmpty(str))
            {
                return str;
            }

            var parts = str.Split('_');
            for (var i = 0; i < parts.Length; i++)
            {
                if (parts[i].Length > 0)
                {
                    parts[i] = char.ToUpper(parts[i][0]) + parts[i].Substring(1);
                }
            }

            return string.Join("", parts);
        }

        private ProtoMessage FindMessage(string name)
        {
            if (_messages.ContainsKey(name))
            {
                return _messages[name];
            }

            foreach (var kvp in _messages)
            {
                if (kvp.Key.EndsWith("." + name) || kvp.Key == name)
                {
                    return kvp.Value;
                }

                var shortName = kvp.Key;
                if (shortName.Contains("."))
                {
                    shortName = shortName.Substring(shortName.LastIndexOf('.') + 1);
                }

                if (shortName == name)
                {
                    return kvp.Value;
                }
            }

            return null;
        }

        private void ParseAllProtos(string rootPath)
        {
            var files = Directory.GetFiles(rootPath, "*.proto", SearchOption.AllDirectories);
            foreach (var file in files) ParseProtoFile(file);
        }

        private void ParseProtoFile(string path)
        {
            var content = File.ReadAllText(path);
            var package = "";

            var packageMatch = Regex.Match(content, @"package\s+([\w\.]+);");
            if (packageMatch.Success)
            {
                package = packageMatch.Groups[1].Value;
            }

            content = Regex.Replace(content, @"//.*", "");

            var lines = content.Split('\n');
            ProtoMessage currentMessage = null;
            string currentOneOf = null;

            foreach (var line in lines)
            {
                var l = line.Trim();
                if (string.IsNullOrEmpty(l))
                {
                    continue;
                }

                if (l.StartsWith("message "))
                {
                    var match = Regex.Match(l, @"message\s+(\w+)\s*\{?");
                    if (match.Success)
                    {
                        var msgName = match.Groups[1].Value;
                        var fullName = string.IsNullOrEmpty(package) ? msgName : package + "." + msgName;
                        currentMessage = new ProtoMessage { Name = fullName, Package = package };
                        _messages[fullName] = currentMessage;
                    }
                }
                else if (l.StartsWith("oneof "))
                {
                    var match = Regex.Match(l, @"oneof\s+(\w+)\s*\{?");
                    if (match.Success)
                    {
                        currentOneOf = match.Groups[1].Value;
                        if (currentMessage != null)
                        {
                            currentMessage.OneOfs.Add(currentOneOf);
                        }
                    }
                }
                else if (l.Contains("}"))
                {
                    if (currentOneOf != null)
                    {
                        if (l.Contains("}"))
                        {
                            currentOneOf = null;
                        }
                    }
                    else if (currentMessage != null)
                    {
                        // 消息结束
                    }
                }
                else if (currentMessage != null)
                {
                    var fieldMatch = Regex.Match(l, @"^([\w\.]+)\s+(\w+)\s*=\s*\d+;");
                    if (fieldMatch.Success)
                    {
                        var field = new ProtoField
                        {
                            Type = fieldMatch.Groups[1].Value,
                            Name = fieldMatch.Groups[2].Value,
                            OneOfGroup = currentOneOf
                        };
                        currentMessage.Fields.Add(field);
                    }
                }
            }
        }
    }
}