using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game.Scripts.Main.Editor.Protobuf
{
    public class HandlerGeneratorInstance
    {
        private readonly Dictionary<string, ProtoMessage> _messages = new();
        private string _outputDirAbs;
        private string _protoRootAbs;

        public void Run()
        {
            _protoRootAbs = Path.Combine(Application.dataPath, "Game", "proto");
            _outputDirAbs = Path.Combine(Application.dataPath, "Game/Scripts/Main/Runtime/Network/Generate");

            if (!Directory.Exists(_outputDirAbs))
            {
                Directory.CreateDirectory(_outputDirAbs);
            }

            _messages.Clear();
            ParseAllProtos(_protoRootAbs);

            foreach (var message in _messages.Values)
                if (message.OneOfs.Any() && !message.Name.Contains("request", StringComparison.OrdinalIgnoreCase))
                {
                    GenerateHandlerForMessage(message);
                }

            AssetDatabase.Refresh();
        }

        private void GenerateHandlerForMessage(ProtoMessage message)
        {
            var messageName = GetCleanMessageName(message.Name);
            var className = $"{ToPascalCase(messageName)}Handler";
            var sb = new StringBuilder();

            var requiredNamespaces = new HashSet<string> { GetCSharpNamespace(message.Package) };
            if (message.OneOfs.Any())
            {
                foreach (var field in message.Fields.Where(f =>
                             !string.IsNullOrEmpty(f.OneOfGroup) &&
                             !f.Name.Contains("service", StringComparison.OrdinalIgnoreCase) &&
                             !f.Name.Contains("request", StringComparison.OrdinalIgnoreCase)))
                {
                    var fullProtoName = FindFullProtoName(field.Type);
                    if (fullProtoName != null && _messages.TryGetValue(fullProtoName, out var fieldMessage))
                    {
                        requiredNamespaces.Add(GetCSharpNamespace(fieldMessage.Package));
                    }
                }
            }


            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("//     Do not modify");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            foreach (var ns in requiredNamespaces.OrderBy(n => n)) sb.AppendLine($"using {ns};");
            sb.AppendLine("using Game.Scripts.Main.Runtime.Network.PacketHandler;");
            sb.AppendLine("using UnityGameFramework.Runtime;");
            sb.AppendLine("using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.Scripts.Main.Runtime.Network.Generate");
            sb.AppendLine("{");
            sb.AppendLine($"    public class {className} : CeleritasHandlerBase<{messageName}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override void Handle(object sender, {messageName} message)");
            sb.AppendLine("        {");

            if (message.OneOfs.Count == 1)
            {
                var oneOfGroup = message.OneOfs.First();
                var oneOfPascal = ToPascalCase(oneOfGroup);
                sb.AppendLine($"            switch (message.{oneOfPascal}Case)");
                sb.AppendLine("            {");

                foreach (var field in message.Fields.Where(f =>
                             f.OneOfGroup == oneOfGroup &&
                             !f.Name.Contains("service", StringComparison.OrdinalIgnoreCase) &&
                             !f.Name.Contains("request", StringComparison.OrdinalIgnoreCase)))
                {
                    var fieldPascal = ToPascalCase(field.Name);
                    var fieldType = GetCSharpTypeName(field.Type);
                    sb.AppendLine($"                case {messageName}.{oneOfPascal}OneofCase.{fieldPascal}:");
                    sb.AppendLine("                {");
                    sb.AppendLine(
                        $"                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<{fieldType}>();");
                    sb.AppendLine("                    if (handler != null)");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        handler.Handle(sender, message.{fieldPascal});");
                    sb.AppendLine("                    }");
                    sb.AppendLine("                    else");
                    sb.AppendLine("                    {");
                    sb.AppendLine($"                        Log.Error(\"Can not find handler for '{field.Name}'.\");");
                    sb.AppendLine("                    }");
                    sb.AppendLine();
                    sb.AppendLine("                    break;");
                    sb.AppendLine("                }");
                }

                sb.AppendLine($"                case {messageName}.{oneOfPascal}OneofCase.None:");
                sb.AppendLine("                {");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
                sb.AppendLine("                default:");
                sb.AppendLine("                {");
                sb.AppendLine(
                    $"                    Log.Warning($\"Unhandled payload case '{{message.{oneOfPascal}Case}}' in message '{messageName}'.\");");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");

                sb.AppendLine("            }");
            }
            else if (message.OneOfs.Any())
            {
                sb.AppendLine("            // Multiple oneof groups are not supported by this generator.");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var finalPath = Path.Combine(_outputDirAbs, $"{className}.cs");
            File.WriteAllText(finalPath, sb.ToString());
            Debug.Log($"Generated handler: {className}.cs");
        }

        private void ParseAllProtos(string rootPath)
        {
            var files = Directory.GetFiles(rootPath, "*.proto", SearchOption.AllDirectories)
                .Where(file =>
                    !file.Contains(Path.DirectorySeparatorChar + "service" + Path.DirectorySeparatorChar) &&
                    !file.Contains(Path.DirectorySeparatorChar + "common" + Path.DirectorySeparatorChar)
                );
            foreach (var file in files) ParseProtoFile(file);
        }

        private void ParseProtoFile(string path)
        {
            var content = File.ReadAllText(path);
            var package = "";

            var packageMatch = Regex.Match(content, @"package\s+([\w\.]+);");
            if (packageMatch.Success)
            {
                package = packageMatch.Groups[1].Value;
            }

            content = Regex.Replace(content, @"//.*", "");

            var lines = content.Split('\n');
            ProtoMessage currentMessage = null;
            string currentOneOf = null;
            var braceDepth = 0;

            foreach (var line in lines)
            {
                var l = line.Trim();
                if (string.IsNullOrEmpty(l))
                {
                    continue;
                }

                if (l.StartsWith("message ") && braceDepth == 0)
                {
                    var match = Regex.Match(l, @"message\s+(\w+)\s*\{?");
                    if (match.Success)
                    {
                        var msgName = match.Groups[1].Value;
                        var fullName = string.IsNullOrEmpty(package) ? msgName : package + "." + msgName;
                        currentMessage = new ProtoMessage { Name = fullName, Package = package };
                        _messages[fullName] = currentMessage;
                    }
                }
                else if (l.StartsWith("oneof ") && braceDepth == 1)
                {
                    var match = Regex.Match(l, @"oneof\s+(\w+)\s*\{?");
                    if (match.Success)
                    {
                        currentOneOf = match.Groups[1].Value;
                        currentMessage?.OneOfs.Add(currentOneOf);
                    }
                }
                else if (currentMessage != null && currentOneOf != null && braceDepth == 2)
                {
                    var fieldMatch = Regex.Match(l, @"^([\w\.]+)\s+(\w+)\s*=\s*\d+;");
                    if (fieldMatch.Success)
                    {
                        var field = new ProtoField
                        {
                            Type = fieldMatch.Groups[1].Value,
                            Name = fieldMatch.Groups[2].Value,
                            OneOfGroup = currentOneOf
                        };
                        currentMessage.Fields.Add(field);
                    }
                }

                if (l.Contains("{"))
                {
                    braceDepth++;
                }

                if (l.Contains("}"))
                {
                    braceDepth--;
                    if (braceDepth == 1 && currentOneOf != null)
                    {
                        currentOneOf = null;
                    }
                    else if (braceDepth == 0 && currentMessage != null)
                    {
                        currentMessage = null;
                    }
                }
            }
        }

        private string FindFullProtoName(string typeName)
        {
            if (_messages.ContainsKey(typeName))
            {
                return typeName;
            }

            var matchingKeys = _messages.Keys.Where(k => k.EndsWith("." + typeName)).ToList();
            if (matchingKeys.Count == 1)
            {
                return matchingKeys[0];
            }

            return null;
        }

        private string GetCSharpNamespace(string protoPackage)
        {
            if (string.IsNullOrEmpty(protoPackage))
            {
                return "Celeritas.Proto";
            }

            return string.Join(".", protoPackage.Split('.').Select(ToPascalCase));
        }

        private string GetCleanMessageName(string protoName)
        {
            if (protoName.Contains("."))
            {
                return protoName.Substring(protoName.LastIndexOf('.') + 1);
            }

            return protoName;
        }

        private string GetCSharpTypeName(string protoType)
        {
            if (protoType.Contains("."))
            {
                return protoType.Substring(protoType.LastIndexOf('.') + 1);
            }

            return protoType;
        }

        private string ToPascalCase(string str)
        {
            if (string.IsNullOrEmpty(str))
            {
                return str;
            }

            return string.Concat(str.Split('_').Select(s =>
            {
                if (string.IsNullOrEmpty(s))
                {
                    return "";
                }

                return char.ToUpper(s[0]) + s.Substring(1);
            }));
        }
    }
}