using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEngine;

namespace Game.Scripts.Main.Editor.Protobuf
{
    public class HandlerGeneratorInstance
    {
        private readonly Dictionary<string, ProtoMessage> _messages = new();
        private readonly string _outputDirAbs = Path.Combine(Application.dataPath, "Game", "Scripts", "Hotfix", "HotfixCommon", "Network", "Generate");
        private readonly string _protoRootAbs = Path.Combine(Application.dataPath, "Game", "proto");

        public void Run()
        {
            if (!Directory.Exists(_outputDirAbs))
            {
                Directory.CreateDirectory(_outputDirAbs);
            }

            _messages.Clear();
            ParseAllProto(_protoRootAbs);

            foreach (var message in _messages.Values.Where(message => message.OneOfs.Any() &&
                                                                      !message.Name.Contains("request", StringComparison.OrdinalIgnoreCase)))
            {
                GenerateHandlerForMessage(message);
            }

            AssetDatabase.Refresh();
        }

        private void GenerateHandlerForMessage(ProtoMessage message)
        {
            var messageName = GetCleanMessageName(message.Name);
            var className = $"{ToPascalCase(messageName)}Handler";
            var stringBuilder = new StringBuilder();

            var requiredNamespaces = CollectRequiredNamespaces(message);
            stringBuilder.Append(GenerateFileHeader(requiredNamespaces));
            stringBuilder.Append(GenerateClassDefinition(message, messageName, className));

            var finalPath = Path.Combine(_outputDirAbs, $"{className}.cs");
            File.WriteAllText(finalPath, stringBuilder.ToString());

            Debug.Log($"Generated handler: {className}.cs");
        }

        private HashSet<string> CollectRequiredNamespaces(ProtoMessage message)
        {
            var requiredNamespaces = new HashSet<string> { GetCSharpNamespace(message.Package) };
            if (!message.OneOfs.Any())
            {
                return requiredNamespaces;
            }

            foreach (var field in message.Fields.Where(f =>
                         !string.IsNullOrEmpty(f.OneOfGroup) &&
                         !f.Name.Contains("service", StringComparison.OrdinalIgnoreCase) &&
                         !f.Name.Contains("request", StringComparison.OrdinalIgnoreCase)))
            {
                var fullProtoName = FindFullProtoName(field.Type);
                if (fullProtoName != null && _messages.TryGetValue(fullProtoName, out var fieldMessage))
                {
                    requiredNamespaces.Add(GetCSharpNamespace(fieldMessage.Package));
                }
            }

            return requiredNamespaces;
        }

        private static StringBuilder GenerateFileHeader(HashSet<string> requiredNamespaces)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("// <auto-generated>");
            stringBuilder.AppendLine("//     This code was generated by a tool.");
            stringBuilder.AppendLine("//     Do not modify");
            stringBuilder.AppendLine("// </auto-generated>");
            stringBuilder.AppendLine();
            foreach (var namespaces in requiredNamespaces.OrderBy(n => n).Where(n => n != "Celeritas.Proto.Common"))
            {
                stringBuilder.AppendLine($"using {namespaces};");
            }

            stringBuilder.AppendLine("using Celeritas.Proto.Common;");
            stringBuilder.AppendLine("using Game.Scripts.Hotfix.HotfixCommon.Network.PacketHandler;");
            stringBuilder.AppendLine("using Game.Scripts.Main.Runtime.Network.PacketHandler;");
            stringBuilder.AppendLine("using UnityGameFramework.Runtime;");
            stringBuilder.AppendLine("using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;");
            stringBuilder.AppendLine();

            return stringBuilder;
        }

        private static StringBuilder GenerateClassDefinition(ProtoMessage message, string messageName, string className)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine("namespace Game.Scripts.Hotfix.HotfixCommon.Network.Generate");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"    public class {className} : CeleritasHandlerBase<{messageName}>");
            stringBuilder.AppendLine("    {");
            stringBuilder.AppendLine($"        protected override void Handle(object sender, header header, {messageName} message)");
            stringBuilder.AppendLine("        {");

            stringBuilder.Append(GenerateHandleMethodBody(message, messageName));

            stringBuilder.AppendLine("        }");
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");

            return stringBuilder;
        }

        private static StringBuilder GenerateHandleMethodBody(ProtoMessage message, string messageName)
        {
            var stringBuilder = new StringBuilder();

            if (message.OneOfs.Count == 1)
            {
                stringBuilder.Append(GenerateSingleOneOfSwitch(message, messageName));
            }
            else if (message.OneOfs.Any())
            {
                stringBuilder.AppendLine("            // Multiple oneof groups are not supported by this generator.");
            }

            return stringBuilder;
        }

        private static StringBuilder GenerateSingleOneOfSwitch(ProtoMessage message, string messageName)
        {
            var stringBuilder = new StringBuilder();
            var oneOfGroup = message.OneOfs.First();
            var oneOfPascal = ToPascalCase(oneOfGroup);

            stringBuilder.AppendLine($"            switch (message.{oneOfPascal}Case)");
            stringBuilder.AppendLine("            {");

            foreach (var field in message.Fields.Where(f =>
                         f.OneOfGroup == oneOfGroup &&
                         !f.Name.Contains("service", StringComparison.OrdinalIgnoreCase) &&
                         !f.Name.Contains("request", StringComparison.OrdinalIgnoreCase)))
            {
                stringBuilder.Append(GenerateSwitchCaseForField(messageName, oneOfPascal, field));
            }

            stringBuilder.Append(GenerateSwitchDefaultCases(messageName, oneOfPascal));

            stringBuilder.AppendLine("            }");

            return stringBuilder;
        }

        private static StringBuilder GenerateSwitchDefaultCases(string messageName, string oneOfPascal)
        {
            var stringBuilder = new StringBuilder();

            stringBuilder.AppendLine($"                case {messageName}.{oneOfPascal}OneofCase.None:");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine("                    break;");
            stringBuilder.AppendLine("                }");
            stringBuilder.AppendLine("                default:");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine($"                    Log.Warning($\"Unhandled payload case '{{message.{oneOfPascal}Case}}' in message '{messageName}'.\");");
            stringBuilder.AppendLine("                    break;");
            stringBuilder.AppendLine("                }");

            return stringBuilder;
        }

        private static StringBuilder GenerateSwitchCaseForField(string messageName, string oneOfPascal, ProtoField field)
        {
            var stringBuilder = new StringBuilder();

            var fieldPascal = ToPascalCase(field.Name);
            var fieldType = GetCSharpTypeName(field.Type);
            stringBuilder.AppendLine($"                case {messageName}.{oneOfPascal}OneofCase.{fieldPascal}:");
            stringBuilder.AppendLine("                {");
            stringBuilder.AppendLine($"                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<{fieldType}>();");
            stringBuilder.AppendLine("                    if (handler != null)");
            stringBuilder.AppendLine("                    {");
            stringBuilder.AppendLine($"                        handler.Handle(sender, header, message.{fieldPascal});");
            stringBuilder.AppendLine("                    }");
            stringBuilder.AppendLine("                    else");
            stringBuilder.AppendLine("                    {");
            stringBuilder.AppendLine($"                        Log.Error(\"Can not find handler for '{field.Name}'.\");");
            stringBuilder.AppendLine("                    }");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("                    break;");
            stringBuilder.AppendLine("                }");

            return stringBuilder;
        }

        private void ParseAllProto(string rootPath)
        {
            var files = Directory.GetFiles(rootPath, "*.proto", SearchOption.AllDirectories)
                .Where(file =>
                    !file.Contains(Path.DirectorySeparatorChar + "service" + Path.DirectorySeparatorChar)
                );

            foreach (var file in files)
            {
                ParseProtoFile(file);
            }
        }

        private void ParseProtoFile(string path)
        {
            var content = File.ReadAllText(path);
            var package = ExtractPackage(content);
            content = RemoveComments(content);
            ParseLines(content.Split('\n'), package);
        }

        private static string ExtractPackage(string content)
        {
            var packageMatch = Regex.Match(content, @"package\s+([\w\.]+);");
            return packageMatch.Success ? packageMatch.Groups[1].Value : "";
        }

        private static string RemoveComments(string content)
        {
            return Regex.Replace(content, "//.*", "");
        }

        private void ParseLines(string[] lines, string package)
        {
            ProtoMessage currentMessage = null;
            string currentOneOf = null;
            var braceDepth = 0;

            foreach (var element in lines)
            {
                var line = element.Trim();
                if (string.IsNullOrEmpty(line))
                {
                    continue;
                }

                switch (braceDepth)
                {
                    case 0:
                    {
                        var message = TryParseMessage(line, package);
                        if (message != null)
                        {
                            currentMessage = message;
                            _messages[currentMessage.Name] = currentMessage;
                        }

                        break;
                    }
                    case 1:
                    {
                        var oneOf = TryParseOneOf(line);
                        if (oneOf != null)
                        {
                            currentOneOf = oneOf;
                            currentMessage?.OneOfs.Add(currentOneOf);
                        }

                        break;
                    }
                    case 2 when currentMessage != null && currentOneOf != null:
                    {
                        var field = TryParseField(line, currentOneOf);
                        if (field != null)
                        {
                            currentMessage.Fields.Add(field);
                        }

                        break;
                    }
                }

                UpdateBraceDepth(line, ref braceDepth, ref currentMessage, ref currentOneOf);
            }
        }

        private static ProtoMessage TryParseMessage(string line, string package)
        {
            if (!line.StartsWith("message "))
            {
                return null;
            }

            var match = Regex.Match(line, @"message\s+(\w+)\s*\{?");
            if (!match.Success)
            {
                return null;
            }

            var msgName = match.Groups[1].Value;
            var fullName = string.IsNullOrEmpty(package) ? msgName : package + "." + msgName;
            return new ProtoMessage { Name = fullName, Package = package };
        }

        private static string TryParseOneOf(string line)
        {
            if (!line.StartsWith("oneof "))
            {
                return null;
            }

            var match = Regex.Match(line, @"oneof\s+(\w+)\s*\{?");
            return !match.Success ? null : match.Groups[1].Value;
        }

        private static ProtoField TryParseField(string line, string currentOneOf)
        {
            var fieldMatch = Regex.Match(line, @"^([\w\.]+)\s+(\w+)\s*=\s*\d+;");
            if (!fieldMatch.Success)
            {
                return null;
            }

            return new ProtoField
            {
                Type = fieldMatch.Groups[1].Value,
                Name = fieldMatch.Groups[2].Value,
                OneOfGroup = currentOneOf
            };
        }

        private static void UpdateBraceDepth(string line, ref int braceDepth, ref ProtoMessage currentMessage, ref string currentOneOf)
        {
            if (line.Contains("{"))
            {
                braceDepth++;
            }

            if (!line.Contains("}"))
            {
                return;
            }

            braceDepth--;
            switch (braceDepth)
            {
                case 1 when currentOneOf != null:
                {
                    currentOneOf = null;
                    break;
                }
                case 0 when currentMessage != null:
                {
                    currentMessage = null;
                    break;
                }
            }
        }

        private string FindFullProtoName(string typeName)
        {
            if (_messages.ContainsKey(typeName))
            {
                return typeName;
            }

            var matchingKeys = _messages.Keys.Where(k => k.EndsWith("." + typeName)).ToList();
            return matchingKeys.Count == 1 ? matchingKeys[0] : null;
        }

        private static string GetCSharpNamespace(string protoPackage)
        {
            return string.IsNullOrEmpty(protoPackage) ? "Celeritas.Proto" : string.Join(".", protoPackage.Split('.').Select(ToPascalCase));
        }

        private static string GetCleanMessageName(string protoName)
        {
            return protoName.Contains(".") ? protoName[(protoName.LastIndexOf('.') + 1)..] : protoName;
        }

        private static string GetCSharpTypeName(string protoType)
        {
            return protoType.Contains(".") ? protoType[(protoType.LastIndexOf('.') + 1)..] : protoType;
        }

        private static string ToPascalCase(string str)
        {
            if (string.IsNullOrEmpty(str))
            {
                return str;
            }

            return string.Concat(str.Split('_').Select(s =>
            {
                if (string.IsNullOrEmpty(s))
                {
                    return "";
                }

                return char.ToUpper(s[0]) + s[1..];
            }));
        }
    }
}    