
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class avatar_config : Luban.BeanBase
{
    public avatar_config(ByteBuf _buf) 
    {
        ItemTemplateId = _buf.ReadInt();
        Quality = (quality_type)_buf.ReadInt();
        Type = (avatar_type)_buf.ReadInt();
        IconRes = _buf.ReadString();
        FullRes = _buf.ReadString();
        UnlockType = (task_event_type)_buf.ReadInt();
        UnlockParam = _buf.ReadInt();
        Hidden = _buf.ReadBool();
        Desc = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Attribute = new System.Collections.Generic.List<attribute_bonus>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { attribute_bonus _e0;  _e0 = global::Celeritas.Config.attribute_bonus.Deserializeattribute_bonus(_buf); Attribute.Add(_e0);}}
    }

    public static avatar_config Deserializeavatar_config(ByteBuf _buf)
    {
        return new game.avatar_config(_buf);
    }

    /// <summary>
    /// 头像编号
    /// </summary>
    public readonly int ItemTemplateId;
    /// <summary>
    /// 品质
    /// </summary>
    public readonly quality_type Quality;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly avatar_type Type;
    /// <summary>
    /// 小图资源路径
    /// </summary>
    public readonly string IconRes;
    /// <summary>
    /// 详情时的资源路径
    /// </summary>
    public readonly string FullRes;
    /// <summary>
    /// 解锁条件类型
    /// </summary>
    public readonly task_event_type UnlockType;
    /// <summary>
    /// 解锁条件参数
    /// </summary>
    public readonly int UnlockParam;
    /// <summary>
    /// 未解锁时是否在列表中可见
    /// </summary>
    public readonly bool Hidden;
    /// <summary>
    /// 获取途径描述文案
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 属性加成
    /// </summary>
    public readonly System.Collections.Generic.List<attribute_bonus> Attribute;
   
    public const int __ID__ = -2081427476;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
        foreach (var _e in Attribute) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "itemTemplateId:" + ItemTemplateId + ","
        + "quality:" + Quality + ","
        + "type:" + Type + ","
        + "iconRes:" + IconRes + ","
        + "fullRes:" + FullRes + ","
        + "unlockType:" + UnlockType + ","
        + "unlockParam:" + UnlockParam + ","
        + "hidden:" + Hidden + ","
        + "desc:" + Desc + ","
        + "attribute:" + Luban.StringUtil.CollectionToString(Attribute) + ","
        + "}";
    }
}
}

