
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class red_dot_config : Luban.BeanBase
{
    public red_dot_config(ByteBuf _buf) 
    {
        Id = (red_dot_type)_buf.ReadInt();
        Name = _buf.ReadString();
        ParentNodeId = (red_dot_type)_buf.ReadInt();
        RedDotStatusType = (red_dot_status_type)_buf.ReadInt();
        SaveDatabase = _buf.ReadBool();
    }

    public static red_dot_config Deserializered_dot_config(ByteBuf _buf)
    {
        return new game.red_dot_config(_buf);
    }

    /// <summary>
    /// 红点类型
    /// </summary>
    public readonly red_dot_type Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 父节点id
    /// </summary>
    public readonly red_dot_type ParentNodeId;
    /// <summary>
    /// 红点状态类型
    /// </summary>
    public readonly red_dot_status_type RedDotStatusType;
    /// <summary>
    /// 是否保存数据库
    /// </summary>
    public readonly bool SaveDatabase;
   
    public const int __ID__ = -1058170654;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "parentNodeId:" + ParentNodeId + ","
        + "redDotStatusType:" + RedDotStatusType + ","
        + "saveDatabase:" + SaveDatabase + ","
        + "}";
    }
}
}

