
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
/// <summary>
/// 改名消耗
/// </summary>
public partial class rename_cost_config_container
{
    private readonly System.Collections.Generic.Dictionary<int, game.rename_cost_config> _dataMap;
    private readonly System.Collections.Generic.List<game.rename_cost_config> _dataList;
    
    public rename_cost_config_container(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, game.rename_cost_config>(n);
        _dataList = new System.Collections.Generic.List<game.rename_cost_config>(n);
        for(int i = n ; i > 0 ; --i)
        {
            game.rename_cost_config _v;
            _v = global::Celeritas.Config.game.rename_cost_config.Deserializerename_cost_config(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, game.rename_cost_config> DataMap => _dataMap;
    public System.Collections.Generic.List<game.rename_cost_config> DataList => _dataList;

    public game.rename_cost_config GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public game.rename_cost_config Get(int key) => _dataMap[key];
    public game.rename_cost_config this[int key] => _dataMap[key];

    public void ResolveRef(tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

