
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class rename_cost_config : Luban.BeanBase
{
    public rename_cost_config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Interval = global::Celeritas.Config.interval.Deserializeinterval(_buf);
        {int n0 = _buf.ReadSize(); PriorityItem = new System.Collections.Generic.List<priority_item>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { priority_item _e0;  _e0 = global::Celeritas.Config.priority_item.Deserializepriority_item(_buf); PriorityItem.Add(_e0);}}
    }

    public static rename_cost_config Deserializerename_cost_config(ByteBuf _buf)
    {
        return new game.rename_cost_config(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 区间
    /// </summary>
    public readonly interval Interval;
    /// <summary>
    /// 所需物品
    /// </summary>
    public readonly System.Collections.Generic.List<priority_item> PriorityItem;
   
    public const int __ID__ = 2043646959;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
        Interval?.ResolveRef(tables);
        foreach (var _e in PriorityItem) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "interval:" + Interval + ","
        + "priorityItem:" + Luban.StringUtil.CollectionToString(PriorityItem) + ","
        + "}";
    }
}
}

