
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class rename_cost_config : Luban.BeanBase
{
    public rename_cost_config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        RenameCount = global::Celeritas.Config.interval.Deserializeinterval(_buf);
        {int n0 = _buf.ReadSize(); Item = new System.Collections.Generic.List<priority_item>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { priority_item _e0;  _e0 = global::Celeritas.Config.priority_item.Deserializepriority_item(_buf); Item.Add(_e0);}}
    }

    public static rename_cost_config Deserializerename_cost_config(ByteBuf _buf)
    {
        return new game.rename_cost_config(_buf);
    }

    /// <summary>
    /// 编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 区间
    /// </summary>
    public readonly interval RenameCount;
    /// <summary>
    /// 所需物品
    /// </summary>
    public readonly System.Collections.Generic.List<priority_item> Item;
   
    public const int __ID__ = 2043646959;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
        RenameCount?.ResolveRef(tables);
        foreach (var _e in Item) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "renameCount:" + RenameCount + ","
        + "item:" + Luban.StringUtil.CollectionToString(Item) + ","
        + "}";
    }
}
}

