
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Celeritas.Config
{ 
    public enum item_type
    {
        /// <summary>
        /// 无
        /// </summary>
        none = 0,
        /// <summary>
        /// 定制
        /// </summary>
        custom = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        consumable = 2,
        /// <summary>
        /// 装备
        /// </summary>
        equipment = 3,
        /// <summary>
        /// 头像
        /// </summary>
        avatar = 4,
        /// <summary>
        /// 头像框
        /// </summary>
        frame = 5,
        /// <summary>
        /// 称号
        /// </summary>
        title = 6,
        /// <summary>
        /// 英雄
        /// </summary>
        hero = 7,
        /// <summary>
        /// 经验
        /// </summary>
        exp = 8,
        /// <summary>
        /// 建筑
        /// </summary>
        building = 9,
        /// <summary>
        /// 资源
        /// </summary>
        resource = 10,
        /// <summary>
        /// 士兵
        /// </summary>
        soldier = 11,
        /// <summary>
        /// 器械
        /// </summary>
        machine = 12,
        /// <summary>
        /// 技能书
        /// </summary>
        skill_book = 13,
        /// <summary>
        /// 图纸
        /// </summary>
        blueprint = 14,
        /// <summary>
        /// 宝箱
        /// </summary>
        gift_box = 15,
        /// <summary>
        /// 珍宝
        /// </summary>
        treasure = 16,
    }

} 

