
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config
{
/// <summary>
/// 物品
/// </summary>
public sealed partial class item : Luban.BeanBase
{
    public item(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        ItemCount = _buf.ReadInt();
    }

    public static item Deserializeitem(ByteBuf _buf)
    {
        return new item(_buf);
    }

    /// <summary>
    /// 物品ID
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 物品数量
    /// </summary>
    public readonly int ItemCount;
   
    public const int __ID__ = 3242771;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "itemCount:" + ItemCount + ","
        + "}";
    }
}
}

