
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Celeritas.Config
{ 
    public enum task_component_type
    {
        /// <summary>
        /// 主线
        /// </summary>
        main = 0,
        /// <summary>
        /// 每日
        /// </summary>
        daily = 1,
        /// <summary>
        /// 头像
        /// </summary>
        avatar = 2,
        /// <summary>
        /// 头像框
        /// </summary>
        frame = 3,
        /// <summary>
        /// 称号
        /// </summary>
        title = 4,
        max = 5,
    }

} 

