
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class event_config : Luban.BeanBase
{
    public event_config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = (event_type)_buf.ReadInt();
        TriggerProbability = _buf.ReadInt();
        Duration = global::Celeritas.Config.interval.Deserializeinterval(_buf);
        {int n0 = _buf.ReadSize(); Buff = new System.Collections.Generic.List<resource_output_bonus>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { resource_output_bonus _e0;  _e0 = global::Celeritas.Config.resource_output_bonus.Deserializeresource_output_bonus(_buf); Buff.Add(_e0);}}
        Comment = _buf.ReadString();
    }

    public static event_config Deserializeevent_config(ByteBuf _buf)
    {
        return new game.event_config(_buf);
    }

    /// <summary>
    /// 事件ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 事件类型
    /// </summary>
    public readonly event_type Type;
    /// <summary>
    /// 触发概率(万分比)
    /// </summary>
    public readonly int TriggerProbability;
    /// <summary>
    /// 持续时间(天数)
    /// </summary>
    public readonly interval Duration;
    /// <summary>
    /// 资源加成Buff
    /// </summary>
    public readonly System.Collections.Generic.List<resource_output_bonus> Buff;
    /// <summary>
    /// 说明注释
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = 1252992259;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
        Duration?.ResolveRef(tables);
        foreach (var _e in Buff) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "triggerProbability:" + TriggerProbability + ","
        + "duration:" + Duration + ","
        + "buff:" + Luban.StringUtil.CollectionToString(Buff) + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

