
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class gather_node_config : Luban.BeanBase
{
    public gather_node_config(ByteBuf _buf) 
    {
        NodeId = _buf.ReadInt();
        ResourceType = (currency_type)_buf.ReadInt();
        Capacity = _buf.ReadInt();
        RefreshTime = _buf.ReadInt();
        MaxGatherCount = _buf.ReadInt();
        Comment = _buf.ReadString();
    }

    public static gather_node_config Deserializegather_node_config(ByteBuf _buf)
    {
        return new game.gather_node_config(_buf);
    }

    /// <summary>
    /// 采集点ID
    /// </summary>
    public readonly int NodeId;
    /// <summary>
    /// 产出资源类型
    /// </summary>
    public readonly currency_type ResourceType;
    /// <summary>
    /// 储量上限
    /// </summary>
    public readonly int Capacity;
    /// <summary>
    /// 刷新周期(秒)
    /// </summary>
    public readonly int RefreshTime;
    /// <summary>
    /// 单日最大采集次数
    /// </summary>
    public readonly int MaxGatherCount;
    /// <summary>
    /// 说明注释
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = 816255831;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "nodeId:" + NodeId + ","
        + "resourceType:" + ResourceType + ","
        + "capacity:" + Capacity + ","
        + "refreshTime:" + RefreshTime + ","
        + "maxGatherCount:" + MaxGatherCount + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

