
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
/// <summary>
/// 帮助手册一级分类
/// </summary>
public partial class help_category_config_container
{
    private readonly System.Collections.Generic.Dictionary<int, game.help_category_config> _dataMap;
    private readonly System.Collections.Generic.List<game.help_category_config> _dataList;
    
    public help_category_config_container(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, game.help_category_config>(n);
        _dataList = new System.Collections.Generic.List<game.help_category_config>(n);
        for(int i = n ; i > 0 ; --i)
        {
            game.help_category_config _v;
            _v = global::Celeritas.Config.game.help_category_config.Deserializehelp_category_config(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, game.help_category_config> DataMap => _dataMap;
    public System.Collections.Generic.List<game.help_category_config> DataList => _dataList;

    public game.help_category_config GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public game.help_category_config Get(int key) => _dataMap[key];
    public game.help_category_config this[int key] => _dataMap[key];

    public void ResolveRef(tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

