
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class maintenance_config : Luban.BeanBase
{
    public maintenance_config(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        TargetId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); CostRate = new System.Collections.Generic.List<resource_output_bonus>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { resource_output_bonus _e0;  _e0 = global::Celeritas.Config.resource_output_bonus.Deserializeresource_output_bonus(_buf); CostRate.Add(_e0);}}
        WildMultiplier = _buf.ReadInt();
        Comment = _buf.ReadString();
    }

    public static maintenance_config Deserializemaintenance_config(ByteBuf _buf)
    {
        return new game.maintenance_config(_buf);
    }

    /// <summary>
    /// 维持条目ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 维持类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 关联目标ID
    /// </summary>
    public readonly int TargetId;
    /// <summary>
    /// 维持消耗速率
    /// </summary>
    public readonly System.Collections.Generic.List<resource_output_bonus> CostRate;
    /// <summary>
    /// 野外粮食消耗系数
    /// </summary>
    public readonly int WildMultiplier;
    /// <summary>
    /// 说明备注
    /// </summary>
    public readonly string Comment;
   
    public const int __ID__ = -1333293718;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
        foreach (var _e in CostRate) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "targetId:" + TargetId + ","
        + "costRate:" + Luban.StringUtil.CollectionToString(CostRate) + ","
        + "wildMultiplier:" + WildMultiplier + ","
        + "comment:" + Comment + ","
        + "}";
    }
}
}

