
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config.game
{
public sealed partial class month_config : Luban.BeanBase
{
    public month_config(ByteBuf _buf) 
    {
        Month = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); ResourceOutput = new System.Collections.Generic.List<resource_output_bonus>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { resource_output_bonus _e0;  _e0 = global::Celeritas.Config.resource_output_bonus.Deserializeresource_output_bonus(_buf); ResourceOutput.Add(_e0);}}
    }

    public static month_config Deserializemonth_config(ByteBuf _buf)
    {
        return new game.month_config(_buf);
    }

    /// <summary>
    /// 月份
    /// </summary>
    public readonly int Month;
    /// <summary>
    /// 资源产出
    /// </summary>
    public readonly System.Collections.Generic.List<resource_output_bonus> ResourceOutput;
   
    public const int __ID__ = -1482889635;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
        foreach (var _e in ResourceOutput) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "month:" + Month + ","
        + "resourceOutput:" + Luban.StringUtil.CollectionToString(ResourceOutput) + ","
        + "}";
    }
}
}

