// <auto-generated>
//     This code was generated by a tool.
//     Do not modify
// </auto-generated>

using Celeritas.Proto;
using Game.Scripts.Main.Runtime.Network.PacketHandler;
using UnityGameFramework.Runtime;
using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;

namespace Game.Scripts.Main.Runtime.Network.Generate
{
    public class CeleritasHandler : CeleritasHandlerBase<celeritas>
    {
        public override void Handle(object sender, celeritas message)
        {
            switch (message.PayloadCase)
            {
                case celeritas.PayloadOneofCase.CeleritasResponse:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, message.CeleritasResponse);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'celeritas_response'.");
                    }

                    break;
                }
                case celeritas.PayloadOneofCase.None:
                {
                    break;
                }
                default:
                {
                    Log.Warning($"Unhandled payload case '{message.PayloadCase}' in message 'celeritas'.");
                    break;
                }
            }
        }
    }
}
