// <auto-generated>
//     This code was generated by a tool.
//     Do not modify
// </auto-generated>

using Celeritas.Proto.Client;
using Celeritas.Proto.Common;
using Game.Scripts.Main.Runtime.Network.PacketHandler;
using UnityGameFramework.Runtime;
using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;

namespace Game.Scripts.Main.Runtime.Network.Generate
{
    public class ClientMailResponseHandler : CeleritasHandlerBase<client_mail_response>
    {
        public override void Handle(object sender, header header, client_mail_response message)
        {
            switch (message.PayloadCase)
            {
                case client_mail_response.PayloadOneofCase.Mail:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<mail_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Mail);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'mail'.");
                    }

                    break;
                }
                case client_mail_response.PayloadOneofCase.MailRead:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<mail_read_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.MailRead);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'mail_read'.");
                    }

                    break;
                }
                case client_mail_response.PayloadOneofCase.MailCollectAttachment:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<mail_collect_attachment_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.MailCollectAttachment);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'mail_collect_attachment'.");
                    }

                    break;
                }
                case client_mail_response.PayloadOneofCase.MailDelete:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<mail_delete_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.MailDelete);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'mail_delete'.");
                    }

                    break;
                }
                case client_mail_response.PayloadOneofCase.MailCollectAllAttachments:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<mail_collect_all_attachments_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.MailCollectAllAttachments);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'mail_collect_all_attachments'.");
                    }

                    break;
                }
                case client_mail_response.PayloadOneofCase.MailDeleteAllRead:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<mail_delete_all_read_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.MailDeleteAllRead);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'mail_delete_all_read'.");
                    }

                    break;
                }
                case client_mail_response.PayloadOneofCase.None:
                {
                    break;
                }
                default:
                {
                    Log.Warning($"Unhandled payload case '{message.PayloadCase}' in message 'client_mail_response'.");
                    break;
                }
            }
        }
    }
}
