// <auto-generated>
//     This code was generated by a tool.
//     Do not modify
// </auto-generated>

using Celeritas.Proto.Client;
using Game.Scripts.Main.Runtime.Network.PacketHandler;
using UnityGameFramework.Runtime;
using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;

namespace Game.Scripts.Main.Runtime.Network.Generate
{
    public class ClientResponseHandler : CeleritasHandlerBase<client_response>
    {
        public override void Handle(object sender, client_response message)
        {
            switch (message.PayloadCase)
            {
                case client_response.PayloadOneofCase.Player:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<client_player_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, message.Player);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'player'.");
                    }

                    break;
                }
                case client_response.PayloadOneofCase.None:
                {
                    break;
                }
                default:
                {
                    Log.Warning($"Unhandled payload case '{message.PayloadCase}' in message 'client_response'.");
                    break;
                }
            }
        }
    }
}
