// <auto-generated>
//     This code was generated by a tool.
//     Do not modify
// </auto-generated>

using Celeritas.Proto.Client;
using Celeritas.Proto.Common;
using Game.Scripts.Main.Runtime.Network.PacketHandler;
using UnityGameFramework.Runtime;
using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;

namespace Game.Scripts.Main.Runtime.Network.Generate
{
    public class InventoryDataHandler : CeleritasHandlerBase<inventory_data>
    {
        public override void Handle(object sender, header header, inventory_data message)
        {
            switch (message.PayloadCase)
            {
                case inventory_data.PayloadOneofCase.Custom:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<custom_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Custom);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'custom'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Consumable:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<consumable_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Consumable);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'consumable'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Equipment:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<equipment_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Equipment);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'equipment'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.None:
                {
                    break;
                }
                default:
                {
                    Log.Warning($"Unhandled payload case '{message.PayloadCase}' in message 'inventory_data'.");
                    break;
                }
            }
        }
    }
}
