// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/client/player/player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Celeritas.Proto.Client {

  /// <summary>Holder for reflection information generated from proto/client/player/player.proto</summary>
  public static partial class PlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/client/player/player.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBwcm90by9jbGllbnQvcGxheWVyL3BsYXllci5wcm90bxIWY2VsZXJpdGFz",
            "LnByb3RvLmNsaWVudBofcHJvdG8vY2xpZW50L3BsYXllci9sb2dpbi5wcm90",
            "bxojcHJvdG8vY2xpZW50L3BsYXllci9oZWFydGJlYXQucHJvdG8aHnByb3Rv",
            "L2NsaWVudC9wbGF5ZXIvcm9sZS5wcm90bxofcHJvdG8vY2xpZW50L3BsYXll",
            "ci9kZWJ1Zy5wcm90bxohcHJvdG8vY2xpZW50L3BsYXllci9yZWRfZG90LnBy",
            "b3RvGh5wcm90by9jbGllbnQvcGxheWVyL2l0ZW0ucHJvdG8aIXByb3RvL2Ns",
            "aWVudC9wbGF5ZXIvZGV2ZWxvcC5wcm90byLnAwoVY2xpZW50X3BsYXllcl9y",
            "ZXF1ZXN0Ej0KBWxvZ2luGAEgASgLMiwuY2VsZXJpdGFzLnByb3RvLmNsaWVu",
            "dC5jbGllbnRfbG9naW5fcmVxdWVzdEgAEkUKCWhlYXJ0YmVhdBgCIAEoCzIw",
            "LmNlbGVyaXRhcy5wcm90by5jbGllbnQuY2xpZW50X2hlYXJ0YmVhdF9yZXF1",
            "ZXN0SAASPQoFZGVidWcYAyABKAsyLC5jZWxlcml0YXMucHJvdG8uY2xpZW50",
            "LmNsaWVudF9kZWJ1Z19yZXF1ZXN0SAASOwoEcm9sZRgEIAEoCzIrLmNlbGVy",
            "aXRhcy5wcm90by5jbGllbnQuY2xpZW50X3JvbGVfcmVxdWVzdEgAEkEKB3Jl",
            "ZF9kb3QYBSABKAsyLi5jZWxlcml0YXMucHJvdG8uY2xpZW50LmNsaWVudF9y",
            "ZWRfZG90X3JlcXVlc3RIABI7CgRpdGVtGAYgASgLMisuY2VsZXJpdGFzLnBy",
            "b3RvLmNsaWVudC5jbGllbnRfaXRlbV9yZXF1ZXN0SAASQQoHZGV2ZWxvcBgH",
            "IAEoCzIuLmNlbGVyaXRhcy5wcm90by5jbGllbnQuY2xpZW50X2RldmVsb3Bf",
            "cmVxdWVzdEgAQgkKB3BheWxvYWQi7wMKFmNsaWVudF9wbGF5ZXJfcmVzcG9u",
            "c2USPgoFbG9naW4YASABKAsyLS5jZWxlcml0YXMucHJvdG8uY2xpZW50LmNs",
            "aWVudF9sb2dpbl9yZXNwb25zZUgAEkYKCWhlYXJ0YmVhdBgCIAEoCzIxLmNl",
            "bGVyaXRhcy5wcm90by5jbGllbnQuY2xpZW50X2hlYXJ0YmVhdF9yZXNwb25z",
            "ZUgAEj4KBWRlYnVnGAMgASgLMi0uY2VsZXJpdGFzLnByb3RvLmNsaWVudC5j",
            "bGllbnRfZGVidWdfcmVzcG9uc2VIABI8CgRyb2xlGAQgASgLMiwuY2VsZXJp",
            "dGFzLnByb3RvLmNsaWVudC5jbGllbnRfcm9sZV9yZXNwb25zZUgAEkIKB3Jl",
            "ZF9kb3QYBSABKAsyLy5jZWxlcml0YXMucHJvdG8uY2xpZW50LmNsaWVudF9y",
            "ZWRfZG90X3Jlc3BvbnNlSAASPAoEaXRlbRgGIAEoCzIsLmNlbGVyaXRhcy5w",
            "cm90by5jbGllbnQuY2xpZW50X2l0ZW1fcmVzcG9uc2VIABJCCgdkZXZlbG9w",
            "GAcgASgLMi8uY2VsZXJpdGFzLnByb3RvLmNsaWVudC5jbGllbnRfZGV2ZWxv",
            "cF9yZXNwb25zZUgAQgkKB3BheWxvYWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Celeritas.Proto.Client.LoginReflection.Descriptor, global::Celeritas.Proto.Client.HeartbeatReflection.Descriptor, global::Celeritas.Proto.Client.RoleReflection.Descriptor, global::Celeritas.Proto.Client.DebugReflection.Descriptor, global::Celeritas.Proto.Client.RedDotReflection.Descriptor, global::Celeritas.Proto.Client.ItemReflection.Descriptor, global::Celeritas.Proto.Client.DevelopReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Client.client_player_request), global::Celeritas.Proto.Client.client_player_request.Parser, new[]{ "Login", "Heartbeat", "Debug", "Role", "RedDot", "Item", "Develop" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Client.client_player_response), global::Celeritas.Proto.Client.client_player_response.Parser, new[]{ "Login", "Heartbeat", "Debug", "Role", "RedDot", "Item", "Develop" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class client_player_request : pb::IMessage<client_player_request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<client_player_request> _parser = new pb::MessageParser<client_player_request>(() => new client_player_request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<client_player_request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Client.PlayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public client_player_request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public client_player_request(client_player_request other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.Login:
          Login = other.Login.Clone();
          break;
        case PayloadOneofCase.Heartbeat:
          Heartbeat = other.Heartbeat.Clone();
          break;
        case PayloadOneofCase.Debug:
          Debug = other.Debug.Clone();
          break;
        case PayloadOneofCase.Role:
          Role = other.Role.Clone();
          break;
        case PayloadOneofCase.RedDot:
          RedDot = other.RedDot.Clone();
          break;
        case PayloadOneofCase.Item:
          Item = other.Item.Clone();
          break;
        case PayloadOneofCase.Develop:
          Develop = other.Develop.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public client_player_request Clone() {
      return new client_player_request(this);
    }

    /// <summary>Field number for the "login" field.</summary>
    public const int LoginFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_login_request Login {
      get { return payloadCase_ == PayloadOneofCase.Login ? (global::Celeritas.Proto.Client.client_login_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Login;
      }
    }

    /// <summary>Field number for the "heartbeat" field.</summary>
    public const int HeartbeatFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_heartbeat_request Heartbeat {
      get { return payloadCase_ == PayloadOneofCase.Heartbeat ? (global::Celeritas.Proto.Client.client_heartbeat_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Heartbeat;
      }
    }

    /// <summary>Field number for the "debug" field.</summary>
    public const int DebugFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_debug_request Debug {
      get { return payloadCase_ == PayloadOneofCase.Debug ? (global::Celeritas.Proto.Client.client_debug_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Debug;
      }
    }

    /// <summary>Field number for the "role" field.</summary>
    public const int RoleFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_role_request Role {
      get { return payloadCase_ == PayloadOneofCase.Role ? (global::Celeritas.Proto.Client.client_role_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Role;
      }
    }

    /// <summary>Field number for the "red_dot" field.</summary>
    public const int RedDotFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_red_dot_request RedDot {
      get { return payloadCase_ == PayloadOneofCase.RedDot ? (global::Celeritas.Proto.Client.client_red_dot_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RedDot;
      }
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_item_request Item {
      get { return payloadCase_ == PayloadOneofCase.Item ? (global::Celeritas.Proto.Client.client_item_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Item;
      }
    }

    /// <summary>Field number for the "develop" field.</summary>
    public const int DevelopFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_develop_request Develop {
      get { return payloadCase_ == PayloadOneofCase.Develop ? (global::Celeritas.Proto.Client.client_develop_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Develop;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Login = 1,
      Heartbeat = 2,
      Debug = 3,
      Role = 4,
      RedDot = 5,
      Item = 6,
      Develop = 7,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as client_player_request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(client_player_request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Login, other.Login)) return false;
      if (!object.Equals(Heartbeat, other.Heartbeat)) return false;
      if (!object.Equals(Debug, other.Debug)) return false;
      if (!object.Equals(Role, other.Role)) return false;
      if (!object.Equals(RedDot, other.RedDot)) return false;
      if (!object.Equals(Item, other.Item)) return false;
      if (!object.Equals(Develop, other.Develop)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.Login) hash ^= Login.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Heartbeat) hash ^= Heartbeat.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Debug) hash ^= Debug.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Role) hash ^= Role.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RedDot) hash ^= RedDot.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Item) hash ^= Item.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Develop) hash ^= Develop.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.Login) {
        output.WriteRawTag(10);
        output.WriteMessage(Login);
      }
      if (payloadCase_ == PayloadOneofCase.Heartbeat) {
        output.WriteRawTag(18);
        output.WriteMessage(Heartbeat);
      }
      if (payloadCase_ == PayloadOneofCase.Debug) {
        output.WriteRawTag(26);
        output.WriteMessage(Debug);
      }
      if (payloadCase_ == PayloadOneofCase.Role) {
        output.WriteRawTag(34);
        output.WriteMessage(Role);
      }
      if (payloadCase_ == PayloadOneofCase.RedDot) {
        output.WriteRawTag(42);
        output.WriteMessage(RedDot);
      }
      if (payloadCase_ == PayloadOneofCase.Item) {
        output.WriteRawTag(50);
        output.WriteMessage(Item);
      }
      if (payloadCase_ == PayloadOneofCase.Develop) {
        output.WriteRawTag(58);
        output.WriteMessage(Develop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.Login) {
        output.WriteRawTag(10);
        output.WriteMessage(Login);
      }
      if (payloadCase_ == PayloadOneofCase.Heartbeat) {
        output.WriteRawTag(18);
        output.WriteMessage(Heartbeat);
      }
      if (payloadCase_ == PayloadOneofCase.Debug) {
        output.WriteRawTag(26);
        output.WriteMessage(Debug);
      }
      if (payloadCase_ == PayloadOneofCase.Role) {
        output.WriteRawTag(34);
        output.WriteMessage(Role);
      }
      if (payloadCase_ == PayloadOneofCase.RedDot) {
        output.WriteRawTag(42);
        output.WriteMessage(RedDot);
      }
      if (payloadCase_ == PayloadOneofCase.Item) {
        output.WriteRawTag(50);
        output.WriteMessage(Item);
      }
      if (payloadCase_ == PayloadOneofCase.Develop) {
        output.WriteRawTag(58);
        output.WriteMessage(Develop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.Login) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Login);
      }
      if (payloadCase_ == PayloadOneofCase.Heartbeat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Heartbeat);
      }
      if (payloadCase_ == PayloadOneofCase.Debug) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Debug);
      }
      if (payloadCase_ == PayloadOneofCase.Role) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Role);
      }
      if (payloadCase_ == PayloadOneofCase.RedDot) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RedDot);
      }
      if (payloadCase_ == PayloadOneofCase.Item) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (payloadCase_ == PayloadOneofCase.Develop) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Develop);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(client_player_request other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Login:
          if (Login == null) {
            Login = new global::Celeritas.Proto.Client.client_login_request();
          }
          Login.MergeFrom(other.Login);
          break;
        case PayloadOneofCase.Heartbeat:
          if (Heartbeat == null) {
            Heartbeat = new global::Celeritas.Proto.Client.client_heartbeat_request();
          }
          Heartbeat.MergeFrom(other.Heartbeat);
          break;
        case PayloadOneofCase.Debug:
          if (Debug == null) {
            Debug = new global::Celeritas.Proto.Client.client_debug_request();
          }
          Debug.MergeFrom(other.Debug);
          break;
        case PayloadOneofCase.Role:
          if (Role == null) {
            Role = new global::Celeritas.Proto.Client.client_role_request();
          }
          Role.MergeFrom(other.Role);
          break;
        case PayloadOneofCase.RedDot:
          if (RedDot == null) {
            RedDot = new global::Celeritas.Proto.Client.client_red_dot_request();
          }
          RedDot.MergeFrom(other.RedDot);
          break;
        case PayloadOneofCase.Item:
          if (Item == null) {
            Item = new global::Celeritas.Proto.Client.client_item_request();
          }
          Item.MergeFrom(other.Item);
          break;
        case PayloadOneofCase.Develop:
          if (Develop == null) {
            Develop = new global::Celeritas.Proto.Client.client_develop_request();
          }
          Develop.MergeFrom(other.Develop);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Celeritas.Proto.Client.client_login_request subBuilder = new global::Celeritas.Proto.Client.client_login_request();
            if (payloadCase_ == PayloadOneofCase.Login) {
              subBuilder.MergeFrom(Login);
            }
            input.ReadMessage(subBuilder);
            Login = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Client.client_heartbeat_request subBuilder = new global::Celeritas.Proto.Client.client_heartbeat_request();
            if (payloadCase_ == PayloadOneofCase.Heartbeat) {
              subBuilder.MergeFrom(Heartbeat);
            }
            input.ReadMessage(subBuilder);
            Heartbeat = subBuilder;
            break;
          }
          case 26: {
            global::Celeritas.Proto.Client.client_debug_request subBuilder = new global::Celeritas.Proto.Client.client_debug_request();
            if (payloadCase_ == PayloadOneofCase.Debug) {
              subBuilder.MergeFrom(Debug);
            }
            input.ReadMessage(subBuilder);
            Debug = subBuilder;
            break;
          }
          case 34: {
            global::Celeritas.Proto.Client.client_role_request subBuilder = new global::Celeritas.Proto.Client.client_role_request();
            if (payloadCase_ == PayloadOneofCase.Role) {
              subBuilder.MergeFrom(Role);
            }
            input.ReadMessage(subBuilder);
            Role = subBuilder;
            break;
          }
          case 42: {
            global::Celeritas.Proto.Client.client_red_dot_request subBuilder = new global::Celeritas.Proto.Client.client_red_dot_request();
            if (payloadCase_ == PayloadOneofCase.RedDot) {
              subBuilder.MergeFrom(RedDot);
            }
            input.ReadMessage(subBuilder);
            RedDot = subBuilder;
            break;
          }
          case 50: {
            global::Celeritas.Proto.Client.client_item_request subBuilder = new global::Celeritas.Proto.Client.client_item_request();
            if (payloadCase_ == PayloadOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 58: {
            global::Celeritas.Proto.Client.client_develop_request subBuilder = new global::Celeritas.Proto.Client.client_develop_request();
            if (payloadCase_ == PayloadOneofCase.Develop) {
              subBuilder.MergeFrom(Develop);
            }
            input.ReadMessage(subBuilder);
            Develop = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Celeritas.Proto.Client.client_login_request subBuilder = new global::Celeritas.Proto.Client.client_login_request();
            if (payloadCase_ == PayloadOneofCase.Login) {
              subBuilder.MergeFrom(Login);
            }
            input.ReadMessage(subBuilder);
            Login = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Client.client_heartbeat_request subBuilder = new global::Celeritas.Proto.Client.client_heartbeat_request();
            if (payloadCase_ == PayloadOneofCase.Heartbeat) {
              subBuilder.MergeFrom(Heartbeat);
            }
            input.ReadMessage(subBuilder);
            Heartbeat = subBuilder;
            break;
          }
          case 26: {
            global::Celeritas.Proto.Client.client_debug_request subBuilder = new global::Celeritas.Proto.Client.client_debug_request();
            if (payloadCase_ == PayloadOneofCase.Debug) {
              subBuilder.MergeFrom(Debug);
            }
            input.ReadMessage(subBuilder);
            Debug = subBuilder;
            break;
          }
          case 34: {
            global::Celeritas.Proto.Client.client_role_request subBuilder = new global::Celeritas.Proto.Client.client_role_request();
            if (payloadCase_ == PayloadOneofCase.Role) {
              subBuilder.MergeFrom(Role);
            }
            input.ReadMessage(subBuilder);
            Role = subBuilder;
            break;
          }
          case 42: {
            global::Celeritas.Proto.Client.client_red_dot_request subBuilder = new global::Celeritas.Proto.Client.client_red_dot_request();
            if (payloadCase_ == PayloadOneofCase.RedDot) {
              subBuilder.MergeFrom(RedDot);
            }
            input.ReadMessage(subBuilder);
            RedDot = subBuilder;
            break;
          }
          case 50: {
            global::Celeritas.Proto.Client.client_item_request subBuilder = new global::Celeritas.Proto.Client.client_item_request();
            if (payloadCase_ == PayloadOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 58: {
            global::Celeritas.Proto.Client.client_develop_request subBuilder = new global::Celeritas.Proto.Client.client_develop_request();
            if (payloadCase_ == PayloadOneofCase.Develop) {
              subBuilder.MergeFrom(Develop);
            }
            input.ReadMessage(subBuilder);
            Develop = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class client_player_response : pb::IMessage<client_player_response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<client_player_response> _parser = new pb::MessageParser<client_player_response>(() => new client_player_response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<client_player_response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Client.PlayerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public client_player_response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public client_player_response(client_player_response other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.Login:
          Login = other.Login.Clone();
          break;
        case PayloadOneofCase.Heartbeat:
          Heartbeat = other.Heartbeat.Clone();
          break;
        case PayloadOneofCase.Debug:
          Debug = other.Debug.Clone();
          break;
        case PayloadOneofCase.Role:
          Role = other.Role.Clone();
          break;
        case PayloadOneofCase.RedDot:
          RedDot = other.RedDot.Clone();
          break;
        case PayloadOneofCase.Item:
          Item = other.Item.Clone();
          break;
        case PayloadOneofCase.Develop:
          Develop = other.Develop.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public client_player_response Clone() {
      return new client_player_response(this);
    }

    /// <summary>Field number for the "login" field.</summary>
    public const int LoginFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_login_response Login {
      get { return payloadCase_ == PayloadOneofCase.Login ? (global::Celeritas.Proto.Client.client_login_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Login;
      }
    }

    /// <summary>Field number for the "heartbeat" field.</summary>
    public const int HeartbeatFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_heartbeat_response Heartbeat {
      get { return payloadCase_ == PayloadOneofCase.Heartbeat ? (global::Celeritas.Proto.Client.client_heartbeat_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Heartbeat;
      }
    }

    /// <summary>Field number for the "debug" field.</summary>
    public const int DebugFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_debug_response Debug {
      get { return payloadCase_ == PayloadOneofCase.Debug ? (global::Celeritas.Proto.Client.client_debug_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Debug;
      }
    }

    /// <summary>Field number for the "role" field.</summary>
    public const int RoleFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_role_response Role {
      get { return payloadCase_ == PayloadOneofCase.Role ? (global::Celeritas.Proto.Client.client_role_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Role;
      }
    }

    /// <summary>Field number for the "red_dot" field.</summary>
    public const int RedDotFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_red_dot_response RedDot {
      get { return payloadCase_ == PayloadOneofCase.RedDot ? (global::Celeritas.Proto.Client.client_red_dot_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RedDot;
      }
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_item_response Item {
      get { return payloadCase_ == PayloadOneofCase.Item ? (global::Celeritas.Proto.Client.client_item_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Item;
      }
    }

    /// <summary>Field number for the "develop" field.</summary>
    public const int DevelopFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Client.client_develop_response Develop {
      get { return payloadCase_ == PayloadOneofCase.Develop ? (global::Celeritas.Proto.Client.client_develop_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Develop;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Login = 1,
      Heartbeat = 2,
      Debug = 3,
      Role = 4,
      RedDot = 5,
      Item = 6,
      Develop = 7,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as client_player_response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(client_player_response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Login, other.Login)) return false;
      if (!object.Equals(Heartbeat, other.Heartbeat)) return false;
      if (!object.Equals(Debug, other.Debug)) return false;
      if (!object.Equals(Role, other.Role)) return false;
      if (!object.Equals(RedDot, other.RedDot)) return false;
      if (!object.Equals(Item, other.Item)) return false;
      if (!object.Equals(Develop, other.Develop)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.Login) hash ^= Login.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Heartbeat) hash ^= Heartbeat.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Debug) hash ^= Debug.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Role) hash ^= Role.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RedDot) hash ^= RedDot.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Item) hash ^= Item.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Develop) hash ^= Develop.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.Login) {
        output.WriteRawTag(10);
        output.WriteMessage(Login);
      }
      if (payloadCase_ == PayloadOneofCase.Heartbeat) {
        output.WriteRawTag(18);
        output.WriteMessage(Heartbeat);
      }
      if (payloadCase_ == PayloadOneofCase.Debug) {
        output.WriteRawTag(26);
        output.WriteMessage(Debug);
      }
      if (payloadCase_ == PayloadOneofCase.Role) {
        output.WriteRawTag(34);
        output.WriteMessage(Role);
      }
      if (payloadCase_ == PayloadOneofCase.RedDot) {
        output.WriteRawTag(42);
        output.WriteMessage(RedDot);
      }
      if (payloadCase_ == PayloadOneofCase.Item) {
        output.WriteRawTag(50);
        output.WriteMessage(Item);
      }
      if (payloadCase_ == PayloadOneofCase.Develop) {
        output.WriteRawTag(58);
        output.WriteMessage(Develop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.Login) {
        output.WriteRawTag(10);
        output.WriteMessage(Login);
      }
      if (payloadCase_ == PayloadOneofCase.Heartbeat) {
        output.WriteRawTag(18);
        output.WriteMessage(Heartbeat);
      }
      if (payloadCase_ == PayloadOneofCase.Debug) {
        output.WriteRawTag(26);
        output.WriteMessage(Debug);
      }
      if (payloadCase_ == PayloadOneofCase.Role) {
        output.WriteRawTag(34);
        output.WriteMessage(Role);
      }
      if (payloadCase_ == PayloadOneofCase.RedDot) {
        output.WriteRawTag(42);
        output.WriteMessage(RedDot);
      }
      if (payloadCase_ == PayloadOneofCase.Item) {
        output.WriteRawTag(50);
        output.WriteMessage(Item);
      }
      if (payloadCase_ == PayloadOneofCase.Develop) {
        output.WriteRawTag(58);
        output.WriteMessage(Develop);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.Login) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Login);
      }
      if (payloadCase_ == PayloadOneofCase.Heartbeat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Heartbeat);
      }
      if (payloadCase_ == PayloadOneofCase.Debug) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Debug);
      }
      if (payloadCase_ == PayloadOneofCase.Role) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Role);
      }
      if (payloadCase_ == PayloadOneofCase.RedDot) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RedDot);
      }
      if (payloadCase_ == PayloadOneofCase.Item) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (payloadCase_ == PayloadOneofCase.Develop) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Develop);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(client_player_response other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Login:
          if (Login == null) {
            Login = new global::Celeritas.Proto.Client.client_login_response();
          }
          Login.MergeFrom(other.Login);
          break;
        case PayloadOneofCase.Heartbeat:
          if (Heartbeat == null) {
            Heartbeat = new global::Celeritas.Proto.Client.client_heartbeat_response();
          }
          Heartbeat.MergeFrom(other.Heartbeat);
          break;
        case PayloadOneofCase.Debug:
          if (Debug == null) {
            Debug = new global::Celeritas.Proto.Client.client_debug_response();
          }
          Debug.MergeFrom(other.Debug);
          break;
        case PayloadOneofCase.Role:
          if (Role == null) {
            Role = new global::Celeritas.Proto.Client.client_role_response();
          }
          Role.MergeFrom(other.Role);
          break;
        case PayloadOneofCase.RedDot:
          if (RedDot == null) {
            RedDot = new global::Celeritas.Proto.Client.client_red_dot_response();
          }
          RedDot.MergeFrom(other.RedDot);
          break;
        case PayloadOneofCase.Item:
          if (Item == null) {
            Item = new global::Celeritas.Proto.Client.client_item_response();
          }
          Item.MergeFrom(other.Item);
          break;
        case PayloadOneofCase.Develop:
          if (Develop == null) {
            Develop = new global::Celeritas.Proto.Client.client_develop_response();
          }
          Develop.MergeFrom(other.Develop);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Celeritas.Proto.Client.client_login_response subBuilder = new global::Celeritas.Proto.Client.client_login_response();
            if (payloadCase_ == PayloadOneofCase.Login) {
              subBuilder.MergeFrom(Login);
            }
            input.ReadMessage(subBuilder);
            Login = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Client.client_heartbeat_response subBuilder = new global::Celeritas.Proto.Client.client_heartbeat_response();
            if (payloadCase_ == PayloadOneofCase.Heartbeat) {
              subBuilder.MergeFrom(Heartbeat);
            }
            input.ReadMessage(subBuilder);
            Heartbeat = subBuilder;
            break;
          }
          case 26: {
            global::Celeritas.Proto.Client.client_debug_response subBuilder = new global::Celeritas.Proto.Client.client_debug_response();
            if (payloadCase_ == PayloadOneofCase.Debug) {
              subBuilder.MergeFrom(Debug);
            }
            input.ReadMessage(subBuilder);
            Debug = subBuilder;
            break;
          }
          case 34: {
            global::Celeritas.Proto.Client.client_role_response subBuilder = new global::Celeritas.Proto.Client.client_role_response();
            if (payloadCase_ == PayloadOneofCase.Role) {
              subBuilder.MergeFrom(Role);
            }
            input.ReadMessage(subBuilder);
            Role = subBuilder;
            break;
          }
          case 42: {
            global::Celeritas.Proto.Client.client_red_dot_response subBuilder = new global::Celeritas.Proto.Client.client_red_dot_response();
            if (payloadCase_ == PayloadOneofCase.RedDot) {
              subBuilder.MergeFrom(RedDot);
            }
            input.ReadMessage(subBuilder);
            RedDot = subBuilder;
            break;
          }
          case 50: {
            global::Celeritas.Proto.Client.client_item_response subBuilder = new global::Celeritas.Proto.Client.client_item_response();
            if (payloadCase_ == PayloadOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 58: {
            global::Celeritas.Proto.Client.client_develop_response subBuilder = new global::Celeritas.Proto.Client.client_develop_response();
            if (payloadCase_ == PayloadOneofCase.Develop) {
              subBuilder.MergeFrom(Develop);
            }
            input.ReadMessage(subBuilder);
            Develop = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Celeritas.Proto.Client.client_login_response subBuilder = new global::Celeritas.Proto.Client.client_login_response();
            if (payloadCase_ == PayloadOneofCase.Login) {
              subBuilder.MergeFrom(Login);
            }
            input.ReadMessage(subBuilder);
            Login = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Client.client_heartbeat_response subBuilder = new global::Celeritas.Proto.Client.client_heartbeat_response();
            if (payloadCase_ == PayloadOneofCase.Heartbeat) {
              subBuilder.MergeFrom(Heartbeat);
            }
            input.ReadMessage(subBuilder);
            Heartbeat = subBuilder;
            break;
          }
          case 26: {
            global::Celeritas.Proto.Client.client_debug_response subBuilder = new global::Celeritas.Proto.Client.client_debug_response();
            if (payloadCase_ == PayloadOneofCase.Debug) {
              subBuilder.MergeFrom(Debug);
            }
            input.ReadMessage(subBuilder);
            Debug = subBuilder;
            break;
          }
          case 34: {
            global::Celeritas.Proto.Client.client_role_response subBuilder = new global::Celeritas.Proto.Client.client_role_response();
            if (payloadCase_ == PayloadOneofCase.Role) {
              subBuilder.MergeFrom(Role);
            }
            input.ReadMessage(subBuilder);
            Role = subBuilder;
            break;
          }
          case 42: {
            global::Celeritas.Proto.Client.client_red_dot_response subBuilder = new global::Celeritas.Proto.Client.client_red_dot_response();
            if (payloadCase_ == PayloadOneofCase.RedDot) {
              subBuilder.MergeFrom(RedDot);
            }
            input.ReadMessage(subBuilder);
            RedDot = subBuilder;
            break;
          }
          case 50: {
            global::Celeritas.Proto.Client.client_item_response subBuilder = new global::Celeritas.Proto.Client.client_item_response();
            if (payloadCase_ == PayloadOneofCase.Item) {
              subBuilder.MergeFrom(Item);
            }
            input.ReadMessage(subBuilder);
            Item = subBuilder;
            break;
          }
          case 58: {
            global::Celeritas.Proto.Client.client_develop_response subBuilder = new global::Celeritas.Proto.Client.client_develop_response();
            if (payloadCase_ == PayloadOneofCase.Develop) {
              subBuilder.MergeFrom(Develop);
            }
            input.ReadMessage(subBuilder);
            Develop = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
