
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Celeritas.Config
{
/// <summary>
/// 属性加成
/// </summary>
public sealed partial class attribute_bonus : Luban.BeanBase
{
    public attribute_bonus(ByteBuf _buf) 
    {
        Type = (attribute_type)_buf.ReadInt();
        Value = _buf.ReadInt();
    }

    public static attribute_bonus Deserializeattribute_bonus(ByteBuf _buf)
    {
        return new attribute_bonus(_buf);
    }

    /// <summary>
    /// 属性类型
    /// </summary>
    public readonly attribute_type Type;
    /// <summary>
    /// 值
    /// </summary>
    public readonly int Value;
   
    public const int __ID__ = -689846084;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "value:" + Value + ","
        + "}";
    }
}
}

