
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Celeritas.Config
{ 
    public enum develop_reset_type
    {
        /// <summary>
        /// 不可重置
        /// </summary>
        non_resettable = 0,
        /// <summary>
        /// 返还
        /// </summary>
        refund = 1,
        /// <summary>
        /// 部分返还
        /// </summary>
        partial_refund = 2,
    }

} 

