
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Celeritas.Config
{ 
    public enum item_type
    {
        /// <summary>
        /// 无
        /// </summary>
        none = 0,
        /// <summary>
        /// 定制
        /// </summary>
        custom = 1,
        /// <summary>
        /// 消耗品
        /// </summary>
        consumable = 2,
        /// <summary>
        /// 装备
        /// </summary>
        equipment = 3,
        /// <summary>
        /// 头像
        /// </summary>
        Avatar = 4,
        /// <summary>
        /// 头像框
        /// </summary>
        Frame = 5,
        /// <summary>
        /// 称号
        /// </summary>
        Title = 6,
        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 7,
    }

} 

