
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Celeritas.Config
{ 
    public enum red_dot_status_type
    {
        /// <summary>
        /// 存在
        /// </summary>
        exist = 0,
        /// <summary>
        /// 和
        /// </summary>
        sum = 1,
    }

} 

