
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Celeritas.Config
{
public partial class tables
{
    public container.surname_config_container SurnameConfigContainer {get; }
    public container.name_config_container NameConfigContainer {get; }
    public container.red_dot_config_container RedDotConfigContainer {get; }
    public container.item_config_container ItemConfigContainer {get; }
    public container.develop_config_container DevelopConfigContainer {get; }

    public tables(System.Func<string, ByteBuf> loader)
    {
        SurnameConfigContainer = new container.surname_config_container(loader("surname_config_container"));
        NameConfigContainer = new container.name_config_container(loader("name_config_container"));
        RedDotConfigContainer = new container.red_dot_config_container(loader("red_dot_config_container"));
        ItemConfigContainer = new container.item_config_container(loader("item_config_container"));
        DevelopConfigContainer = new container.develop_config_container(loader("develop_config_container"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        SurnameConfigContainer.ResolveRef(this);
        NameConfigContainer.ResolveRef(this);
        RedDotConfigContainer.ResolveRef(this);
        ItemConfigContainer.ResolveRef(this);
        DevelopConfigContainer.ResolveRef(this);
    }
}

}
