// <auto-generated>
//     This code was generated by a tool.
//     Do not modify
// </auto-generated>

using Celeritas.Proto.Client;
using Celeritas.Proto.Common;
using Game.Scripts.Hotfix.HotfixCommon.Network.PacketHandler;
using Game.Scripts.Main.Runtime.Network.PacketHandler;
using UnityGameFramework.Runtime;
using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;

namespace Game.Scripts.Hotfix.HotfixCommon.Network.Generate
{
    public class ClientDevelopResponseHandler : CeleritasHandlerBase<client_develop_response>
    {
        protected override void Handle(object sender, header header, client_develop_response message)
        {
            switch (message.PayloadCase)
            {
                case client_develop_response.PayloadOneofCase.Develop:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<develop_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Develop);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'develop'.");
                    }

                    break;
                }
                case client_develop_response.PayloadOneofCase.DevelopLevel:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<develop_level_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.DevelopLevel);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'develop_level'.");
                    }

                    break;
                }
                case client_develop_response.PayloadOneofCase.DevelopReset:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<develop_reset_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.DevelopReset);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'develop_reset'.");
                    }

                    break;
                }
                case client_develop_response.PayloadOneofCase.DevelopClaimReward:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<develop_claim_reward_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.DevelopClaimReward);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'develop_claim_reward'.");
                    }

                    break;
                }
                case client_develop_response.PayloadOneofCase.None:
                {
                    break;
                }
                default:
                {
                    Log.Warning($"Unhandled payload case '{message.PayloadCase}' in message 'client_develop_response'.");
                    break;
                }
            }
        }
    }
}
