// <auto-generated>
//     This code was generated by a tool.
//     Do not modify
// </auto-generated>

using Celeritas.Proto.Client;
using Celeritas.Proto.Common;
using Game.Scripts.Hotfix.HotfixCommon.Network.PacketHandler;
using Game.Scripts.Main.Runtime.Network.PacketHandler;
using UnityGameFramework.Runtime;
using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;

namespace Game.Scripts.Hotfix.HotfixCommon.Network.Generate
{
    public class ClientRoleResponseHandler : CeleritasHandlerBase<client_role_response>
    {
        protected override void Handle(object sender, header header, client_role_response message)
        {
            switch (message.PayloadCase)
            {
                case client_role_response.PayloadOneofCase.Role:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<role_response>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Role);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'role'.");
                    }

                    break;
                }
                case client_role_response.PayloadOneofCase.None:
                {
                    break;
                }
                default:
                {
                    Log.Warning($"Unhandled payload case '{message.PayloadCase}' in message 'client_role_response'.");
                    break;
                }
            }
        }
    }
}
