// <auto-generated>
//     This code was generated by a tool.
//     Do not modify
// </auto-generated>

using Celeritas.Proto.Common;
using Game.Scripts.Hotfix.HotfixCommon.Network.PacketHandler;
using Game.Scripts.Main.Runtime.Network.PacketHandler;
using UnityGameFramework.Runtime;
using GameEntry = Game.Scripts.Main.Runtime.Base.GameEntry;

namespace Game.Scripts.Hotfix.HotfixCommon.Network.Generate
{
    public class InventoryDataHandler : CeleritasHandlerBase<inventory_data>
    {
        protected override void Handle(object sender, header header, inventory_data message)
        {
            switch (message.PayloadCase)
            {
                case inventory_data.PayloadOneofCase.Custom:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<custom_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Custom);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'custom'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Consumable:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<consumable_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Consumable);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'consumable'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Equipment:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<equipment_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Equipment);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'equipment'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Avatar:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<avatar_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Avatar);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'avatar'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Frame:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<frame_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Frame);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'frame'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Title:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<title_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Title);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'title'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Hero:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<hero_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Hero);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'hero'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Exp:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<exp_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Exp);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'exp'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Building:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<building_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Building);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'building'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Resource:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<resource_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Resource);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'resource'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Soldier:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<soldier_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Soldier);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'soldier'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Machine:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<machine_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Machine);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'machine'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.SkillBook:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<skill_book_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.SkillBook);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'skill_book'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Blueprint:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<blueprint_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Blueprint);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'blueprint'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.GiftBox:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<gift_box_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.GiftBox);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'gift_box'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.Treasure:
                {
                    var handler = GameEntry.CeleritasHandler.GetCeleritasHandler<treasure_data>();
                    if (handler != null)
                    {
                        handler.Handle(sender, header, message.Treasure);
                    }
                    else
                    {
                        Log.Error("Can not find handler for 'treasure'.");
                    }

                    break;
                }
                case inventory_data.PayloadOneofCase.None:
                {
                    break;
                }
                default:
                {
                    Log.Warning($"Unhandled payload case '{message.PayloadCase}' in message 'inventory_data'.");
                    break;
                }
            }
        }
    }
}
