// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/service/player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Celeritas.Proto.Service {

  /// <summary>Holder for reflection information generated from proto/service/player.proto</summary>
  public static partial class PlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/service/player.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chpwcm90by9zZXJ2aWNlL3BsYXllci5wcm90bxIXY2VsZXJpdGFzLnByb3Rv",
            "LnNlcnZpY2UiNwoYcmVsb2FkX2NvbmZpZ19kYl9yZXF1ZXN0Eg8KB2RiX25h",
            "bWUYASABKAkSCgoCaWQYAiABKAMiGwoZcmVsb2FkX2NvbmZpZ19kYl9yZXNw",
            "b25zZSLbAQoVc2VydmljZV9sb2dpbl9yZXF1ZXN0EhIKCmFjY291bnRfaWQY",
            "ASABKAMSEwoLbmV3X2FjY291bnQYAiABKAgSFwoPYWNjb3VudF9iaW5kX2lk",
            "GAMgASgDEhoKEm5ld19nYW1lX3NlcnZlcl9pZBgEIAEoCBIWCg5nYW1lX3Nl",
            "cnZlcl9pZBgFIAEoCRIRCglkZXZpY2VfaWQYBiABKAkSEwoLYXBwX3ZlcnNp",
            "b24YByABKAkSEgoKc2Vzc2lvbl9pZBgIIAEoAxIQCghwcm90b2NvbBgJIAEo",
            "BSJpChZzZXJ2aWNlX2xvZ2luX3Jlc3BvbnNlEhQKDGN1cnJlbnRfdGltZRgB",
            "IAEoAxISCgpzZXNzaW9uX2lkGAIgASgDEhAKCHByb3RvY29sGAMgASgFEhMK",
            "C2luc3RhbmNlX2lkGAQgASgJIrsBChZzZXJ2aWNlX3BsYXllcl9yZXF1ZXN0",
            "Ek0KEHJlbG9hZF9jb25maWdfZGIYASABKAsyMS5jZWxlcml0YXMucHJvdG8u",
            "c2VydmljZS5yZWxvYWRfY29uZmlnX2RiX3JlcXVlc3RIABJHCg1zZXJ2aWNl",
            "X2xvZ2luGAIgASgLMi4uY2VsZXJpdGFzLnByb3RvLnNlcnZpY2Uuc2Vydmlj",
            "ZV9sb2dpbl9yZXF1ZXN0SABCCQoHcGF5bG9hZCK+AQoXc2VydmljZV9wbGF5",
            "ZXJfcmVzcG9uc2USTgoQcmVsb2FkX2NvbmZpZ19kYhgBIAEoCzIyLmNlbGVy",
            "aXRhcy5wcm90by5zZXJ2aWNlLnJlbG9hZF9jb25maWdfZGJfcmVzcG9uc2VI",
            "ABJICg1zZXJ2aWNlX2xvZ2luGAIgASgLMi8uY2VsZXJpdGFzLnByb3RvLnNl",
            "cnZpY2Uuc2VydmljZV9sb2dpbl9yZXNwb25zZUgAQgkKB3BheWxvYWRiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Service.reload_config_db_request), global::Celeritas.Proto.Service.reload_config_db_request.Parser, new[]{ "DbName", "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Service.reload_config_db_response), global::Celeritas.Proto.Service.reload_config_db_response.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Service.service_login_request), global::Celeritas.Proto.Service.service_login_request.Parser, new[]{ "AccountId", "NewAccount", "AccountBindId", "NewGameServerId", "GameServerId", "DeviceId", "AppVersion", "SessionId", "Protocol" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Service.service_login_response), global::Celeritas.Proto.Service.service_login_response.Parser, new[]{ "CurrentTime", "SessionId", "Protocol", "InstanceId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Service.service_player_request), global::Celeritas.Proto.Service.service_player_request.Parser, new[]{ "ReloadConfigDb", "ServiceLogin" }, new[]{ "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Service.service_player_response), global::Celeritas.Proto.Service.service_player_response.Parser, new[]{ "ReloadConfigDb", "ServiceLogin" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 重载配置数据库
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class reload_config_db_request : pb::IMessage<reload_config_db_request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<reload_config_db_request> _parser = new pb::MessageParser<reload_config_db_request>(() => new reload_config_db_request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<reload_config_db_request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Service.PlayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public reload_config_db_request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public reload_config_db_request(reload_config_db_request other) : this() {
      dbName_ = other.dbName_;
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public reload_config_db_request Clone() {
      return new reload_config_db_request(this);
    }

    /// <summary>Field number for the "db_name" field.</summary>
    public const int DbNameFieldNumber = 1;
    private string dbName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DbName {
      get { return dbName_; }
      set {
        dbName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as reload_config_db_request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(reload_config_db_request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DbName != other.DbName) return false;
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DbName.Length != 0) hash ^= DbName.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DbName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DbName);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DbName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DbName);
      }
      if (Id != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DbName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DbName);
      }
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(reload_config_db_request other) {
      if (other == null) {
        return;
      }
      if (other.DbName.Length != 0) {
        DbName = other.DbName;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DbName = input.ReadString();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            DbName = input.ReadString();
            break;
          }
          case 16: {
            Id = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class reload_config_db_response : pb::IMessage<reload_config_db_response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<reload_config_db_response> _parser = new pb::MessageParser<reload_config_db_response>(() => new reload_config_db_response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<reload_config_db_response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Service.PlayerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public reload_config_db_response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public reload_config_db_response(reload_config_db_response other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public reload_config_db_response Clone() {
      return new reload_config_db_response(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as reload_config_db_response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(reload_config_db_response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(reload_config_db_response other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class service_login_request : pb::IMessage<service_login_request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<service_login_request> _parser = new pb::MessageParser<service_login_request>(() => new service_login_request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<service_login_request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Service.PlayerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_login_request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_login_request(service_login_request other) : this() {
      accountId_ = other.accountId_;
      newAccount_ = other.newAccount_;
      accountBindId_ = other.accountBindId_;
      newGameServerId_ = other.newGameServerId_;
      gameServerId_ = other.gameServerId_;
      deviceId_ = other.deviceId_;
      appVersion_ = other.appVersion_;
      sessionId_ = other.sessionId_;
      protocol_ = other.protocol_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_login_request Clone() {
      return new service_login_request(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private long accountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "new_account" field.</summary>
    public const int NewAccountFieldNumber = 2;
    private bool newAccount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NewAccount {
      get { return newAccount_; }
      set {
        newAccount_ = value;
      }
    }

    /// <summary>Field number for the "account_bind_id" field.</summary>
    public const int AccountBindIdFieldNumber = 3;
    private long accountBindId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AccountBindId {
      get { return accountBindId_; }
      set {
        accountBindId_ = value;
      }
    }

    /// <summary>Field number for the "new_game_server_id" field.</summary>
    public const int NewGameServerIdFieldNumber = 4;
    private bool newGameServerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NewGameServerId {
      get { return newGameServerId_; }
      set {
        newGameServerId_ = value;
      }
    }

    /// <summary>Field number for the "game_server_id" field.</summary>
    public const int GameServerIdFieldNumber = 5;
    private string gameServerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameServerId {
      get { return gameServerId_; }
      set {
        gameServerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "device_id" field.</summary>
    public const int DeviceIdFieldNumber = 6;
    private string deviceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeviceId {
      get { return deviceId_; }
      set {
        deviceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "app_version" field.</summary>
    public const int AppVersionFieldNumber = 7;
    private string appVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AppVersion {
      get { return appVersion_; }
      set {
        appVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 8;
    private long sessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = value;
      }
    }

    /// <summary>Field number for the "protocol" field.</summary>
    public const int ProtocolFieldNumber = 9;
    private int protocol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Protocol {
      get { return protocol_; }
      set {
        protocol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as service_login_request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(service_login_request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (NewAccount != other.NewAccount) return false;
      if (AccountBindId != other.AccountBindId) return false;
      if (NewGameServerId != other.NewGameServerId) return false;
      if (GameServerId != other.GameServerId) return false;
      if (DeviceId != other.DeviceId) return false;
      if (AppVersion != other.AppVersion) return false;
      if (SessionId != other.SessionId) return false;
      if (Protocol != other.Protocol) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId != 0L) hash ^= AccountId.GetHashCode();
      if (NewAccount != false) hash ^= NewAccount.GetHashCode();
      if (AccountBindId != 0L) hash ^= AccountBindId.GetHashCode();
      if (NewGameServerId != false) hash ^= NewGameServerId.GetHashCode();
      if (GameServerId.Length != 0) hash ^= GameServerId.GetHashCode();
      if (DeviceId.Length != 0) hash ^= DeviceId.GetHashCode();
      if (AppVersion.Length != 0) hash ^= AppVersion.GetHashCode();
      if (SessionId != 0L) hash ^= SessionId.GetHashCode();
      if (Protocol != 0) hash ^= Protocol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AccountId);
      }
      if (NewAccount != false) {
        output.WriteRawTag(16);
        output.WriteBool(NewAccount);
      }
      if (AccountBindId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AccountBindId);
      }
      if (NewGameServerId != false) {
        output.WriteRawTag(32);
        output.WriteBool(NewGameServerId);
      }
      if (GameServerId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GameServerId);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DeviceId);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(AppVersion);
      }
      if (SessionId != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(SessionId);
      }
      if (Protocol != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Protocol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AccountId);
      }
      if (NewAccount != false) {
        output.WriteRawTag(16);
        output.WriteBool(NewAccount);
      }
      if (AccountBindId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AccountBindId);
      }
      if (NewGameServerId != false) {
        output.WriteRawTag(32);
        output.WriteBool(NewGameServerId);
      }
      if (GameServerId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GameServerId);
      }
      if (DeviceId.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(DeviceId);
      }
      if (AppVersion.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(AppVersion);
      }
      if (SessionId != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(SessionId);
      }
      if (Protocol != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Protocol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountId);
      }
      if (NewAccount != false) {
        size += 1 + 1;
      }
      if (AccountBindId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountBindId);
      }
      if (NewGameServerId != false) {
        size += 1 + 1;
      }
      if (GameServerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameServerId);
      }
      if (DeviceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeviceId);
      }
      if (AppVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AppVersion);
      }
      if (SessionId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SessionId);
      }
      if (Protocol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Protocol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(service_login_request other) {
      if (other == null) {
        return;
      }
      if (other.AccountId != 0L) {
        AccountId = other.AccountId;
      }
      if (other.NewAccount != false) {
        NewAccount = other.NewAccount;
      }
      if (other.AccountBindId != 0L) {
        AccountBindId = other.AccountBindId;
      }
      if (other.NewGameServerId != false) {
        NewGameServerId = other.NewGameServerId;
      }
      if (other.GameServerId.Length != 0) {
        GameServerId = other.GameServerId;
      }
      if (other.DeviceId.Length != 0) {
        DeviceId = other.DeviceId;
      }
      if (other.AppVersion.Length != 0) {
        AppVersion = other.AppVersion;
      }
      if (other.SessionId != 0L) {
        SessionId = other.SessionId;
      }
      if (other.Protocol != 0) {
        Protocol = other.Protocol;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AccountId = input.ReadInt64();
            break;
          }
          case 16: {
            NewAccount = input.ReadBool();
            break;
          }
          case 24: {
            AccountBindId = input.ReadInt64();
            break;
          }
          case 32: {
            NewGameServerId = input.ReadBool();
            break;
          }
          case 42: {
            GameServerId = input.ReadString();
            break;
          }
          case 50: {
            DeviceId = input.ReadString();
            break;
          }
          case 58: {
            AppVersion = input.ReadString();
            break;
          }
          case 64: {
            SessionId = input.ReadInt64();
            break;
          }
          case 72: {
            Protocol = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AccountId = input.ReadInt64();
            break;
          }
          case 16: {
            NewAccount = input.ReadBool();
            break;
          }
          case 24: {
            AccountBindId = input.ReadInt64();
            break;
          }
          case 32: {
            NewGameServerId = input.ReadBool();
            break;
          }
          case 42: {
            GameServerId = input.ReadString();
            break;
          }
          case 50: {
            DeviceId = input.ReadString();
            break;
          }
          case 58: {
            AppVersion = input.ReadString();
            break;
          }
          case 64: {
            SessionId = input.ReadInt64();
            break;
          }
          case 72: {
            Protocol = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class service_login_response : pb::IMessage<service_login_response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<service_login_response> _parser = new pb::MessageParser<service_login_response>(() => new service_login_response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<service_login_response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Service.PlayerReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_login_response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_login_response(service_login_response other) : this() {
      currentTime_ = other.currentTime_;
      sessionId_ = other.sessionId_;
      protocol_ = other.protocol_;
      instanceId_ = other.instanceId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_login_response Clone() {
      return new service_login_response(this);
    }

    /// <summary>Field number for the "current_time" field.</summary>
    public const int CurrentTimeFieldNumber = 1;
    private long currentTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CurrentTime {
      get { return currentTime_; }
      set {
        currentTime_ = value;
      }
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 2;
    private long sessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = value;
      }
    }

    /// <summary>Field number for the "protocol" field.</summary>
    public const int ProtocolFieldNumber = 3;
    private int protocol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Protocol {
      get { return protocol_; }
      set {
        protocol_ = value;
      }
    }

    /// <summary>Field number for the "instance_id" field.</summary>
    public const int InstanceIdFieldNumber = 4;
    private string instanceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InstanceId {
      get { return instanceId_; }
      set {
        instanceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as service_login_response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(service_login_response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CurrentTime != other.CurrentTime) return false;
      if (SessionId != other.SessionId) return false;
      if (Protocol != other.Protocol) return false;
      if (InstanceId != other.InstanceId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CurrentTime != 0L) hash ^= CurrentTime.GetHashCode();
      if (SessionId != 0L) hash ^= SessionId.GetHashCode();
      if (Protocol != 0) hash ^= Protocol.GetHashCode();
      if (InstanceId.Length != 0) hash ^= InstanceId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CurrentTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CurrentTime);
      }
      if (SessionId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SessionId);
      }
      if (Protocol != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Protocol);
      }
      if (InstanceId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InstanceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CurrentTime != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CurrentTime);
      }
      if (SessionId != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SessionId);
      }
      if (Protocol != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Protocol);
      }
      if (InstanceId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InstanceId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CurrentTime != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CurrentTime);
      }
      if (SessionId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SessionId);
      }
      if (Protocol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Protocol);
      }
      if (InstanceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InstanceId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(service_login_response other) {
      if (other == null) {
        return;
      }
      if (other.CurrentTime != 0L) {
        CurrentTime = other.CurrentTime;
      }
      if (other.SessionId != 0L) {
        SessionId = other.SessionId;
      }
      if (other.Protocol != 0) {
        Protocol = other.Protocol;
      }
      if (other.InstanceId.Length != 0) {
        InstanceId = other.InstanceId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CurrentTime = input.ReadInt64();
            break;
          }
          case 16: {
            SessionId = input.ReadInt64();
            break;
          }
          case 24: {
            Protocol = input.ReadInt32();
            break;
          }
          case 34: {
            InstanceId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CurrentTime = input.ReadInt64();
            break;
          }
          case 16: {
            SessionId = input.ReadInt64();
            break;
          }
          case 24: {
            Protocol = input.ReadInt32();
            break;
          }
          case 34: {
            InstanceId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class service_player_request : pb::IMessage<service_player_request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<service_player_request> _parser = new pb::MessageParser<service_player_request>(() => new service_player_request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<service_player_request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Service.PlayerReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_player_request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_player_request(service_player_request other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.ReloadConfigDb:
          ReloadConfigDb = other.ReloadConfigDb.Clone();
          break;
        case PayloadOneofCase.ServiceLogin:
          ServiceLogin = other.ServiceLogin.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_player_request Clone() {
      return new service_player_request(this);
    }

    /// <summary>Field number for the "reload_config_db" field.</summary>
    public const int ReloadConfigDbFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Service.reload_config_db_request ReloadConfigDb {
      get { return payloadCase_ == PayloadOneofCase.ReloadConfigDb ? (global::Celeritas.Proto.Service.reload_config_db_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ReloadConfigDb;
      }
    }

    /// <summary>Field number for the "service_login" field.</summary>
    public const int ServiceLoginFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Service.service_login_request ServiceLogin {
      get { return payloadCase_ == PayloadOneofCase.ServiceLogin ? (global::Celeritas.Proto.Service.service_login_request) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ServiceLogin;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      ReloadConfigDb = 1,
      ServiceLogin = 2,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as service_player_request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(service_player_request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ReloadConfigDb, other.ReloadConfigDb)) return false;
      if (!object.Equals(ServiceLogin, other.ServiceLogin)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) hash ^= ReloadConfigDb.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) hash ^= ServiceLogin.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
        output.WriteRawTag(10);
        output.WriteMessage(ReloadConfigDb);
      }
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
        output.WriteRawTag(18);
        output.WriteMessage(ServiceLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
        output.WriteRawTag(10);
        output.WriteMessage(ReloadConfigDb);
      }
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
        output.WriteRawTag(18);
        output.WriteMessage(ServiceLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReloadConfigDb);
      }
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServiceLogin);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(service_player_request other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.ReloadConfigDb:
          if (ReloadConfigDb == null) {
            ReloadConfigDb = new global::Celeritas.Proto.Service.reload_config_db_request();
          }
          ReloadConfigDb.MergeFrom(other.ReloadConfigDb);
          break;
        case PayloadOneofCase.ServiceLogin:
          if (ServiceLogin == null) {
            ServiceLogin = new global::Celeritas.Proto.Service.service_login_request();
          }
          ServiceLogin.MergeFrom(other.ServiceLogin);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Celeritas.Proto.Service.reload_config_db_request subBuilder = new global::Celeritas.Proto.Service.reload_config_db_request();
            if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
              subBuilder.MergeFrom(ReloadConfigDb);
            }
            input.ReadMessage(subBuilder);
            ReloadConfigDb = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Service.service_login_request subBuilder = new global::Celeritas.Proto.Service.service_login_request();
            if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
              subBuilder.MergeFrom(ServiceLogin);
            }
            input.ReadMessage(subBuilder);
            ServiceLogin = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Celeritas.Proto.Service.reload_config_db_request subBuilder = new global::Celeritas.Proto.Service.reload_config_db_request();
            if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
              subBuilder.MergeFrom(ReloadConfigDb);
            }
            input.ReadMessage(subBuilder);
            ReloadConfigDb = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Service.service_login_request subBuilder = new global::Celeritas.Proto.Service.service_login_request();
            if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
              subBuilder.MergeFrom(ServiceLogin);
            }
            input.ReadMessage(subBuilder);
            ServiceLogin = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class service_player_response : pb::IMessage<service_player_response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<service_player_response> _parser = new pb::MessageParser<service_player_response>(() => new service_player_response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<service_player_response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Service.PlayerReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_player_response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_player_response(service_player_response other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.ReloadConfigDb:
          ReloadConfigDb = other.ReloadConfigDb.Clone();
          break;
        case PayloadOneofCase.ServiceLogin:
          ServiceLogin = other.ServiceLogin.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_player_response Clone() {
      return new service_player_response(this);
    }

    /// <summary>Field number for the "reload_config_db" field.</summary>
    public const int ReloadConfigDbFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Service.reload_config_db_response ReloadConfigDb {
      get { return payloadCase_ == PayloadOneofCase.ReloadConfigDb ? (global::Celeritas.Proto.Service.reload_config_db_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ReloadConfigDb;
      }
    }

    /// <summary>Field number for the "service_login" field.</summary>
    public const int ServiceLoginFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Service.service_login_response ServiceLogin {
      get { return payloadCase_ == PayloadOneofCase.ServiceLogin ? (global::Celeritas.Proto.Service.service_login_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ServiceLogin;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      ReloadConfigDb = 1,
      ServiceLogin = 2,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as service_player_response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(service_player_response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ReloadConfigDb, other.ReloadConfigDb)) return false;
      if (!object.Equals(ServiceLogin, other.ServiceLogin)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) hash ^= ReloadConfigDb.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) hash ^= ServiceLogin.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
        output.WriteRawTag(10);
        output.WriteMessage(ReloadConfigDb);
      }
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
        output.WriteRawTag(18);
        output.WriteMessage(ServiceLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
        output.WriteRawTag(10);
        output.WriteMessage(ReloadConfigDb);
      }
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
        output.WriteRawTag(18);
        output.WriteMessage(ServiceLogin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReloadConfigDb);
      }
      if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServiceLogin);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(service_player_response other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.ReloadConfigDb:
          if (ReloadConfigDb == null) {
            ReloadConfigDb = new global::Celeritas.Proto.Service.reload_config_db_response();
          }
          ReloadConfigDb.MergeFrom(other.ReloadConfigDb);
          break;
        case PayloadOneofCase.ServiceLogin:
          if (ServiceLogin == null) {
            ServiceLogin = new global::Celeritas.Proto.Service.service_login_response();
          }
          ServiceLogin.MergeFrom(other.ServiceLogin);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Celeritas.Proto.Service.reload_config_db_response subBuilder = new global::Celeritas.Proto.Service.reload_config_db_response();
            if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
              subBuilder.MergeFrom(ReloadConfigDb);
            }
            input.ReadMessage(subBuilder);
            ReloadConfigDb = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Service.service_login_response subBuilder = new global::Celeritas.Proto.Service.service_login_response();
            if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
              subBuilder.MergeFrom(ServiceLogin);
            }
            input.ReadMessage(subBuilder);
            ServiceLogin = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Celeritas.Proto.Service.reload_config_db_response subBuilder = new global::Celeritas.Proto.Service.reload_config_db_response();
            if (payloadCase_ == PayloadOneofCase.ReloadConfigDb) {
              subBuilder.MergeFrom(ReloadConfigDb);
            }
            input.ReadMessage(subBuilder);
            ReloadConfigDb = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Service.service_login_response subBuilder = new global::Celeritas.Proto.Service.service_login_response();
            if (payloadCase_ == PayloadOneofCase.ServiceLogin) {
              subBuilder.MergeFrom(ServiceLogin);
            }
            input.ReadMessage(subBuilder);
            ServiceLogin = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
