// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/service/service_response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Celeritas.Proto.Service {

  /// <summary>Holder for reflection information generated from proto/service/service_response.proto</summary>
  public static partial class ServiceResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/service/service_response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRwcm90by9zZXJ2aWNlL3NlcnZpY2VfcmVzcG9uc2UucHJvdG8SF2NlbGVy",
            "aXRhcy5wcm90by5zZXJ2aWNlGhxwcm90by9zZXJ2aWNlL3JlZ2lzdHJ5LnBy",
            "b3RvGhhwcm90by9zZXJ2aWNlL2F1dGgucHJvdG8aG3Byb3RvL3NlcnZpY2Uv",
            "cGF5bWVudC5wcm90byLrAQoQc2VydmljZV9yZXNwb25zZRJGCghyZWdpc3Ry",
            "eRgBIAEoCzIyLmNlbGVyaXRhcy5wcm90by5zZXJ2aWNlLnNlcnZpY2VfcmVn",
            "aXN0cnlfcmVzcG9uc2VIABI+CgRhdXRoGAIgASgLMi4uY2VsZXJpdGFzLnBy",
            "b3RvLnNlcnZpY2Uuc2VydmljZV9hdXRoX3Jlc3BvbnNlSAASRAoHcGF5bWVu",
            "dBgDIAEoCzIxLmNlbGVyaXRhcy5wcm90by5zZXJ2aWNlLnNlcnZpY2VfcGF5",
            "bWVudF9yZXNwb25zZUgAQgkKB3BheWxvYWRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Celeritas.Proto.Service.RegistryReflection.Descriptor, global::Celeritas.Proto.Service.AuthReflection.Descriptor, global::Celeritas.Proto.Service.PaymentReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Celeritas.Proto.Service.service_response), global::Celeritas.Proto.Service.service_response.Parser, new[]{ "Registry", "Auth", "Payment" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class service_response : pb::IMessage<service_response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<service_response> _parser = new pb::MessageParser<service_response>(() => new service_response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<service_response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Celeritas.Proto.Service.ServiceResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_response(service_response other) : this() {
      switch (other.PayloadCase) {
        case PayloadOneofCase.Registry:
          Registry = other.Registry.Clone();
          break;
        case PayloadOneofCase.Auth:
          Auth = other.Auth.Clone();
          break;
        case PayloadOneofCase.Payment:
          Payment = other.Payment.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public service_response Clone() {
      return new service_response(this);
    }

    /// <summary>Field number for the "registry" field.</summary>
    public const int RegistryFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Service.service_registry_response Registry {
      get { return payloadCase_ == PayloadOneofCase.Registry ? (global::Celeritas.Proto.Service.service_registry_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Registry;
      }
    }

    /// <summary>Field number for the "auth" field.</summary>
    public const int AuthFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Service.service_auth_response Auth {
      get { return payloadCase_ == PayloadOneofCase.Auth ? (global::Celeritas.Proto.Service.service_auth_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Auth;
      }
    }

    /// <summary>Field number for the "payment" field.</summary>
    public const int PaymentFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Celeritas.Proto.Service.service_payment_response Payment {
      get { return payloadCase_ == PayloadOneofCase.Payment ? (global::Celeritas.Proto.Service.service_payment_response) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Payment;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Registry = 1,
      Auth = 2,
      Payment = 3,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as service_response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(service_response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Registry, other.Registry)) return false;
      if (!object.Equals(Auth, other.Auth)) return false;
      if (!object.Equals(Payment, other.Payment)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (payloadCase_ == PayloadOneofCase.Registry) hash ^= Registry.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Auth) hash ^= Auth.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Payment) hash ^= Payment.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (payloadCase_ == PayloadOneofCase.Registry) {
        output.WriteRawTag(10);
        output.WriteMessage(Registry);
      }
      if (payloadCase_ == PayloadOneofCase.Auth) {
        output.WriteRawTag(18);
        output.WriteMessage(Auth);
      }
      if (payloadCase_ == PayloadOneofCase.Payment) {
        output.WriteRawTag(26);
        output.WriteMessage(Payment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (payloadCase_ == PayloadOneofCase.Registry) {
        output.WriteRawTag(10);
        output.WriteMessage(Registry);
      }
      if (payloadCase_ == PayloadOneofCase.Auth) {
        output.WriteRawTag(18);
        output.WriteMessage(Auth);
      }
      if (payloadCase_ == PayloadOneofCase.Payment) {
        output.WriteRawTag(26);
        output.WriteMessage(Payment);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (payloadCase_ == PayloadOneofCase.Registry) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Registry);
      }
      if (payloadCase_ == PayloadOneofCase.Auth) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Auth);
      }
      if (payloadCase_ == PayloadOneofCase.Payment) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payment);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(service_response other) {
      if (other == null) {
        return;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Registry:
          if (Registry == null) {
            Registry = new global::Celeritas.Proto.Service.service_registry_response();
          }
          Registry.MergeFrom(other.Registry);
          break;
        case PayloadOneofCase.Auth:
          if (Auth == null) {
            Auth = new global::Celeritas.Proto.Service.service_auth_response();
          }
          Auth.MergeFrom(other.Auth);
          break;
        case PayloadOneofCase.Payment:
          if (Payment == null) {
            Payment = new global::Celeritas.Proto.Service.service_payment_response();
          }
          Payment.MergeFrom(other.Payment);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Celeritas.Proto.Service.service_registry_response subBuilder = new global::Celeritas.Proto.Service.service_registry_response();
            if (payloadCase_ == PayloadOneofCase.Registry) {
              subBuilder.MergeFrom(Registry);
            }
            input.ReadMessage(subBuilder);
            Registry = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Service.service_auth_response subBuilder = new global::Celeritas.Proto.Service.service_auth_response();
            if (payloadCase_ == PayloadOneofCase.Auth) {
              subBuilder.MergeFrom(Auth);
            }
            input.ReadMessage(subBuilder);
            Auth = subBuilder;
            break;
          }
          case 26: {
            global::Celeritas.Proto.Service.service_payment_response subBuilder = new global::Celeritas.Proto.Service.service_payment_response();
            if (payloadCase_ == PayloadOneofCase.Payment) {
              subBuilder.MergeFrom(Payment);
            }
            input.ReadMessage(subBuilder);
            Payment = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Celeritas.Proto.Service.service_registry_response subBuilder = new global::Celeritas.Proto.Service.service_registry_response();
            if (payloadCase_ == PayloadOneofCase.Registry) {
              subBuilder.MergeFrom(Registry);
            }
            input.ReadMessage(subBuilder);
            Registry = subBuilder;
            break;
          }
          case 18: {
            global::Celeritas.Proto.Service.service_auth_response subBuilder = new global::Celeritas.Proto.Service.service_auth_response();
            if (payloadCase_ == PayloadOneofCase.Auth) {
              subBuilder.MergeFrom(Auth);
            }
            input.ReadMessage(subBuilder);
            Auth = subBuilder;
            break;
          }
          case 26: {
            global::Celeritas.Proto.Service.service_payment_response subBuilder = new global::Celeritas.Proto.Service.service_payment_response();
            if (payloadCase_ == PayloadOneofCase.Payment) {
              subBuilder.MergeFrom(Payment);
            }
            input.ReadMessage(subBuilder);
            Payment = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
